### ISSUE TITLE
Replace custom i18n functions with Gutenberg utilities

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#101]
It looks like G now provides a JS version of `sprintf()` in the `wp.i18n` package, and probably a few other helps as well.

I don't think those existed when we first started working on this, which is why we built `tokenSplit`, etc, but those can probably be replaced now.

**Comment by coreymckrill** [comment]
The `sprintf()` actually did exist already, but it doesn't solve the problem that `tokenSplit` and `arrayTokenReplace` are meant to address.

The problem is that you can't add a single string of content as a child of a React element if it contains HTML, because it will convert the HTML tags to literal characters, unless you use `dangerouslySetHTML`. This problem arises when you have a translated string that contains links or other HTML elements that might be in a different order when translated into another language.

I introduced `tokenSplit` and `arrayTokenReplace` [here](https://github.com/WordPress/wordcamp.org/pull/33/commits/bbe3ce87af54a66449e7408f71cdbfab10b59bb5) to try and address this in a way that is compatible with WP's established convention for tokenizing translatable strings. 

The doc blocks on those functions don't include examples that have React elements in them, so maybe it's not clear how they are different. But you can see an example of the intended use in the [Sessions block](https://github.com/WordPress/wordcamp.org/blob/d38ba179a21cc223ae67a6aece1dde70f146fc74/public_html/wp-content/mu-plugins/blocks/assets/src/sessions/block-content.js#L66-L81).

**Comment by iandunn** [comment]
👍 Thanks for the insight :)
