### ISSUE TITLE
WordCamp banner for prior year sites does not direct visitors to the current-year WC site

### ISSUE THREAD

**Issue by hellojuliarose** [WordPress/wordcamp.org#1258]
**Describe the bug**
Though WordCamp US 2024 is 7 months away, the organizers proactively created a WordCamp US 2025 site so we can begin sharing information about WCUS 2025 _before_ WCUS 2024 concludes.

The banner at the top of prior years' WCUS sites (2023 and earlier) reads:

> WordCamp US [year] is over. Check out [the next edition](https://us.wordcamp.org/2025/)!

The banner links to us.wordcamp.org/2025, rather than to the current WordCamp US site: us.wordcamp.org/2024.

**To reproduce**
1. Go to us.wordcamp.org/2023
2. Click on the banner at top of page: "WordCamp US 2023 is over. Check out [the next edition](https://us.wordcamp.org/2025/)!"
3. Observe that the site directs to WCUS 2025 rather than WCUS 2024.

**Expected behavior**
I would expect that the previous years' banners would redirect to the current WordCamp year (rather than to the highest WC year).

**Screenshots**
<img width="802" alt="Screenshot 2024-02-27 at 11 16 46 AM" src="https://github.com/WordPress/wordcamp.org/assets/131417782/3e731114-0e8d-4c80-a518-82eb82b322e0">

**Comment by pkevan** [comment]
There seem to be a few issues with this banner ([#](https://github.com/WordPress/wordcamp.org/pull/1239)), so wondering if we should make it an optional switch off, or revisit the logic completely, since it's complicated and there appears to be quite a few edge cases.

Original PR: https://github.com/WordPress/wordcamp.org/pull/725

**Comment by hellojuliarose** [comment]
> wondering if we should make it an optional switch off

@pkevan an optional off-switch would be excellent!

> or revisit the logic completely, since it's complicated and there appears to be quite a few edge cases

I'm not directly familiar with the logic, so I defer to the Meta team to decide whether this is doable and would help

**Comment by ryelle** [comment]
This link should probably use the same logic (same function?) that the redirect code uses, if possible - that's updated to not redirect prematurely for the flagship events. 

>> so wondering if we should make it an optional switch off
>
> an optional off-switch would be excellent!

Where would the switch off be, on the 2025 site or on the older sites?

**Comment by pkevan** [comment]
> Where would the switch off be, on the 2025 site or on the older sites?

Yeah, not sure - it just seems like there are quite a few problems with the current code, and wanted an easy way to avoid it being on.

**Comment by ryelle** [comment]
I spent a little time trying to use the `get_canonical_year_url` function to work, but it seems like it's only meant to be called once, [this logic returns false](https://github.com/WordPress/wordcamp.org/blob/086ef14ebcf6db08fd61f53129a845cf96c4ad1d/public_html/wp-content/sunrise-wordcamp.php#L571-L593) because the site info is always cached on subsequent calls. 

Maybe the date checks can be moved into `get_latest_site`, and then we can use that? Then at least the logic will all be consistent… ah, but that all won't exist on events.w.org. Ugh.

> wanted an easy way to avoid it being on.

[A feature flag](https://github.com/WordPress/wordcamp.org/blob/086ef14ebcf6db08fd61f53129a845cf96c4ad1d/public_html/wp-content/mu-plugins/wp-cli-commands/miscellaneous.php#L13) could work, we could set the flag on the old WCUS sites & then check `if ( ! wcorg_skip_feature( 'latest-site-hint' ) )`? That would definitely be the easiest route.

**Comment by pkevan** [comment]
This was resolved in https://github.com/WordPress/wordcamp.org/pull/1260, by setting a skip_feature `latest-site-hint`. Not sure if we wanted to do other sites, but I removed it from 2023 version.

**Comment by dd32** [comment]
Just noting that this resolution is actually not ideal from another perspective..

Now that the US & EU 2023 sites have this flag set, they don't get a banner directing visitors to the current year sites.

The proper resolution here probably would've been to change the functionality to find the next soonest open wordcamp, rather than just a future open wordcamp.

FYI @pkevan  since this now causes other confusion, like as seen here: https://wordpress.slack.com/archives/C02QB8GMM/p1716987108673809

**Comment by pkevan** [comment]
>FYI @pkevan since this now causes other confusion, like as seen here:

Thanks - yeah, this functionality is difficult to understand and has many edge cases. My preference would be to remove it and start again.
