### ISSUE TITLE
Day of Event Template: Decide on strings for "on now" & "up next" headings

### ISSUE THREAD

**Issue by avillegasn** [WordPress/wordcamp.org#127]
We should use the texts 'On now' and 'Up next' in the day-of-event template here:

https://github.com/WordPress/wordcamp.org/blob/42a361e9f20e642f8d4d6eb037049265e3e60143/public_html/wp-content/mu-plugins/theme-templates/templates/day-of-event/src/components/schedule.js#L115

and here:

https://github.com/WordPress/wordcamp.org/blob/42a361e9f20e642f8d4d6eb037049265e3e60143/public_html/wp-content/mu-plugins/theme-templates/templates/day-of-event/src/components/schedule.js#L122

**Comment by iandunn** [comment]
🤔 , I changed it because the old strings felt ambiguous to me, but I'm definitely open to changing them back, or to something new that's better than both.

Can you articulate why "On Now" and "Up Next" feel more clear to you?

To me, "On now" feels kind of vague and open to interpretation, even with the context of it being a heading for the sessions. "In Progress" feels like a more familiar description for this kind of situation, but that's definitely anecdotal.

"Coming up next" feels like it just adds context/detail to "up next", without taking anything away from it. I'm curious to understand what I could be missing, though.

I think it'd be good to get some broader feedback to suss out the pros/cons, too. I'll ask the Polyglots team if they have any feedback. To provide context for them and anyone else, here's a screenshot of what this part of the page looks like:

<img width="714" alt="Screen Shot 2019-06-20 at 7 09 13 AM" src="https://user-images.githubusercontent.com/484068/59857457-db166480-932d-11e9-8691-2afab2670440.png">

**Comment by naokomc** [comment]
Perspective from a Japanese translator: "On now" and "Up next" are not easy to translate by themselves. But if there is a well-written translator's comment, I don't mind.

**Comment by andreamiddleton** [comment]
@avillegasn, the terms "On Now" and "Up Next" are very short, which I think leaves them open to a little interpretation, which then makes them a little less clear... Is the preference for those terms based on a desire to keep the headings very short because of small screens? Or do those terms tie into something else WordCamp Europe is doing, or is there some other reasons they're very important terms to keep?

**Comment by avillegasn** [comment]
We feel that "On now" and "Up next" are short and snappy and completely clear and unambiguous. Because of their brevity they don´t add to the cognitive load when users are searching for timely information as quickly and efficiently as possible.

We also feel that "In progress" is less clear that this is something happening now, as "in progress" is something that is often applied to longer term things where one might say something like "this is a work in progress". "On now" says exactly what it means, just as you might say about, for example, a TV  program - it´s on now.

Additionally "Coming on next" doesn´t really add any additional meaning to "On next" and increases the cognitive load for the user.

We would prefer that the terms were reverted to the originals.

**Comment by iandunn** [comment]
🤔 I can see your point about "in progress" sometimes referring to a longer-term activity. "On now" still feels less clear and more ambiguous to me, though. Like, it makes me think, "on what?", because of the physical connotations of "on". Maybe that's just me, though?

I wonder if "Happening now" might be better than either of those? It's longer than "On now", but I think clarity is much more important than brevity.

Personally, I have a hard time imagining that "Coming up next" would present a larger cognitive load than "Up next"; if anything it seems like it's less difficult, because it's less ambiguous.

Having said all that, those are just how the words seem to me, personally. Ideally we'd have more time to get more input from Polyglots, to get a broad spectrum of people, but we may just need to pick something for now, and potentially update it after WCEU, once we have more feedback.

**Comment by iandunn** [comment]
cb99e19c6898458107e2f224dfec684697b508db reverts to the previous strings, to give us more time to consider the best long term solution.
