### ISSUE TITLE
Send Attendee Survey for 3 (Three) WordPress Events

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/wordcamp.org#1287]
The Attendees Survey for new WordPress Events is automated and [should be sent as soon as the event is completed](https://github.com/WordPress/wordcamp.org/pull/1069). However, due to [an issue](https://a8c.slack.com/archives/C204BD7PT/p1708634072937279), some events were affected and didn't receive the survey. The issue has been fixed, and we want to resend the Attendee Survey for 3 (three) events for reporting purposes:

1. [Women WordPress Day](https://central.wordcamp.org/wp-admin/post.php?post=5304941&action=edit) - March 8, 2024
2. [Switzerland Community Day](https://central.wordcamp.org/wp-admin/post.php?post=4350606&action=edit) - March 23, 2024
3. [WordPress in Education Technology Showcase](https://central.wordcamp.org/wp-admin/post.php?post=3559525&action=edit) - April 6, 2024

The Attendee Survey Report on WordCamp Central Dashboard: 

<img width="966" alt="Screenshot 2024-04-16 at 10 10 17" src="https://github.com/WordPress/wordcamp.org/assets/75025757/de6d0dc3-8736-4019-9a90-458b8a218896">

**Comment by outdoor2kode** [comment]
Just noted: Following the steps described here, running `wc_attendee_survey_email` doesn't change the post status in ticket->email from draft to pending. Perhaps it needs setting the end date to 2 days ago. ~A local testing is needed.~

**Update**
Yep. It needs to be exactly two days. [Ref](https://github.com/WordPress/wordcamp.org/pull/997/files#diff-c2ea6049ff5b587f55cf1fd62ab2094d2d8c4a42adbb69d2083b25984f9d0494R133).

**Comment by outdoor2kode** [comment]
Hey @devinmaeztri 👋 I've sent out attendee surveys for the designated three events as requested, thanks for raising the issue.

And here's the record of the process for manually sending them: cc @pkevan 

Since the [code](https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/camptix-attendee-survey/includes/cron.php#L134) is set to send the survey exactly 2 days after an event ends, so it needs using the sandbox to adjust the setting to > 2 days (`return gmdate('Y-m-d', $send_date) < current_time('Y-m-d', true)`) to make the cron job be able to be manually triggered.

1. After adjusting, check under the event site dashboard's tickets > email to see if there is a draft post with the title: `[first_name], tell us what you thought: Post-event survey`.
2. In the sandbox's `wordcamp/public_html` directory, run `wp cron event list --url={event site url}`.
    * I have an alias for `wp`, otherwise, the general path is under the bin in wporg.
3. You will see two jobs: `wc_attendee_survey_email` and `tix_scheduled_every_ten_minutes`.
4. Run `wp cron event run wc_attendee_survey_email --url={event site url}`.
5. If successful, you will see that the status of `[first_name], tell us what you thought: Post-event survey` changes to pending.
6. Then execute `wp cron event run tix_scheduled_every_ten_minutes --url={event site url}`.
7. The post status will change to published, indicating the email has been sent. Can also check the total sent counts at `https://central.wordcamp.org/wp-admin/admin.php?page=attendee_survey`.
8. To this, all processes are completed. Then we just wait for two weeks, and the cron job `wc_attendee_disable_survey` will automatically run to close the survey and stop it from being filled out. This does NOT require manual execution from us.

Reference PR: https://github.com/WordPress/wordcamp.org/pull/997

**Comment by devinmaeztri** [comment]
Thank you, Ren!
