### ISSUE TITLE
 Request to add font for bretagne.wordcamp.org/2024

### ISSUE THREAD

**Issue by alexandrebuffet** [WordPress/wordcamp.org#1306]
Related Issue: #1075 

I'm currently integrating the site [WordCamp Bretagne](https://bretagne.wordcamp.org/2024/) with the Twenty Twenty-Four theme and the site editor but I can't manage to install "Unbounded" font from Google Fonts with the new Font Library.

Can someone here add "Unbounded" font to the site ?

`@import url('https://fonts.googleapis.com/css2?family=Unbounded:wght@200..900&display=swap');`

We also use "Inter", but the font is already integrated into the theme.

Thanks!

**Comment by dd32** [comment]
```
URL https://bretagne.wordcamp.org/2024/wp-json/wp/v2/font-families/319/font-faces?_locale=user
E_ERROR Maximum execution time of 100 seconds exceeded
```

Just noting that this is caused by a out-of-time limit, Most likely due to an infinite loop caused by the flux in where fonts were stored. 8954265aa4c2786a447466eee884b17d70088e54 was added to WordCamp to store it in uploads. But as of https://github.com/WordPress/wordpress-develop/commit/f8e1870778cadf3bd48d03fb4e53fd144686ffe9 I believe the change on WordCamp is no longer needed, right @peterwilsoncc?

**Comment by peterwilsoncc** [comment]
@dd32 That's correct -- 8954265aa4c2786a447466eee884b17d70088e54 can safely be reverted.

**Comment by dd32** [comment]
Verified that font install appears to work on the site in question; @alexandrebuffet can you confirm?

**Comment by alexandrebuffet** [comment]
Looks good to me! I was able to install the font in question without error from the Font Library. Thanks!
