### ISSUE TITLE
Blocks: Allow centering of content in addition to images

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#141]
Currently, it's possible to center the image for example, in the Speakers block:

![Screen Shot 2019-07-09 at 6 04 08 PM](https://user-images.githubusercontent.com/541093/60926371-4475fd00-a274-11e9-88e9-f1135c952b3e.png)

But if I want the speaker name to be centered above that (for example, [the Boston speakers list](https://2019.boston.wordcamp.org/speakers/)), I need to add custom CSS. We could maybe use the alignment in the toolbar to set the block's text alignment? Like paragraph:

![Screen Shot 2019-07-09 at 6 04 54 PM](https://user-images.githubusercontent.com/541093/60926372-4475fd00-a274-11e9-87b8-ffae31bd882f.png)

Should this be content-type specific (so title and excerpt are individually aligned), or should it always be the same (if it's centered, both title and content will be centered)? @melchoyce, thoughts?

**Comment by coreymckrill** [comment]
I feel like adding three more buttons to the block controls is a lot of additional clutter. But I also see the utility in having an easy way to align the content.

If we did add the buttons, I would prefer to keep it simple, and have it align all the content (except the image, I guess, since it has its own controls for that). If someone wants to align different parts of the content in different ways, that's where I would draw the line and say, "you need to add your own CSS".

**Comment by melchoyce** [comment]
I like the idea of being able to center the speaker name, but most of the bios I've seen are long enough that centering them is a bad idea. I'd be more inclined to add a sidebar setting for centering the name, like the header block currently has.
