### ISSUE TITLE
JS Code Standards: Alignment of objects, keys & values

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#148]
_This is one of a few issues/PRs dealing with code standards, created after a discussion in slack._

Currently we align object parameters on their assignment operator (`:`), so that this is considered correct.

```js
{
	entityType : 'post',
	type       : 'wcb_sponsor',
	label      : __( 'Sponsors', 'wordcamporg' ),
	items      : wcb_sponsor,
},
```

The code standards for this project are overriding core's code standards, which say that there should be no spaces before `:` in an object definition. [source](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#spacing)

As a WordPress community project, we should be following the core coding standards so that anyone involved in a core project can jump into our codebase without needing to learn a new style. This would facilitate community contributions due to faster onboarding. 

The eslint rules we're overriding are `key-spacing` and `no-multi-spaces`. By overriding `no-multi-spaces` we're also opening the possibility of incorrect spacing elsewhere in the code. This issue is to suggest we remove both these overrides, and fall back to the core standards here, so that our "correct" format of the above would be:

```js
{
	entityType: 'post',
	type: 'wcb_sponsor',
	label: __( 'Sponsors', 'wordcamporg' ),
	items: wcb_sponsor,
},
```

(see https://github.com/WordPress/wordcamp.org/issues/149 for more on `no-multi-spaces`)

**Comment by ryelle** [comment]
as a note, this is considered correct - not _all_ keys need to line up, something about being broken apart by the child object means the alignment of keys above/below the object are considered separate. Attempting to align the `:` for all top-level keys results in spacing errors

Correct:

```js
const test = {
	key : 'value',
	foo : {
		a : 'value',
		b : 'value',
	},
	bar               : 'value',
	veryLongAttribute : 'value',
};
```

Incorrect:

```js
const test = {
	key               : 'value',
	foo               : {
		a : 'value',
		b : 'value',
	},
	bar               : 'value',
	veryLongAttribute : 'value',
};
```

**Comment by iandunn** [comment]
### In General

> As a WordPress community project, we should be following the core coding standards so that anyone involved in a core project can jump into our codebase without needing to learn a new style. 

I agree that we should start with them as our basis, but I think it's totally fine to deviate from them when it'd make a significant impact on readability for project committers. The standards chosen by Core are only meant to apply to Core:

>> While reading these changes, it’s important to keep in mind that they only apply to WordPress Core: you can (and should) choose practices that best suits your development style for your own plugins and themes. The coding standards are intentionally opinionated, and will always lean towards readability and accessibility over being able to use every possible language feature. ([>>](https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/))

We operate in a different context, especially when it comes to the distribution of time spent contributing. I'd roughly guess than 95% of the time spent on WordCamp.org is from you, myself, and @coreymckrill, which is a very different situation than Core. In that context, I think it makes sense to optimize for our what fits the 3 of us best, while still maintaining fundamental consistency with Core, so that the standards feel familiar.

There are other contextual differences as well, like the fact that we can use newer language features without worrying about back-compat.

> This would facilitate community contributions due to faster onboarding.

I don't personally see coding standards as being a significant barrier for contributors, especially since the deviations are relatively minor. If they are, though, I'd be perfectly happy to let people submit patches using whatever standard is easiest for them, and committers can apply them during the merge process. 

That's be much less painful for me than having to work with less-readable code the other 99% of the time.

You did make a compelling argument earlier about the lack of tooling support for non-"idiomatic" standards. I agree that it's much easier to just do what everybody else does, and I don't think it'd be worth it to write custom linting rules to enforce our deviations. For me, though, the pain of making some manual tweaks is much less than the pain of difficult-to-read code, so I'd ultimately favor deviating where we can agree that it'd help us.

In cases where we can't agree, then it probably does make the most sense to err on the side of consistency with Core.


### `key-spacing` / `no-multi-spaces` specifically

Personally, I find things much, much easier to read when they're aligned to show the similarities / highlight the differences. It also makes it much quicker for me to parse at a glance and understand what's going on. Unaligned code looks very messy and cluttered to me, and I have to slow down and slowly read each line in order to grok it.

There are cases where that breaks down, like this:

```js
import { ItemTitle, DangerousItemHTMLContent, ItemPermalink, BlockNoContent } from '../../components/block-content';
import { FeaturedImage }                                                      from '../../components/image';
import { PostList }                                                           from '../../components/post-list';
import { filterEntities }                                                     from '../../data';
import { tokenSplit, arrayTokenReplace }                                      from '../../i18n';
```

In cases like that, I'd be in favor of ignoring the outlier and doing this:

```js
import { ItemTitle, DangerousItemHTMLContent, ItemPermalink, BlockNoContent } from '../../components/block-content';
import { FeaturedImage }                  from '../../components/image';
import { PostList }                       from '../../components/post-list';
import { filterEntities }                 from '../../data';
import { tokenSplit, arrayTokenReplace  } from '../../i18n';
```

**Comment by coreymckrill** [comment]
What I perceive here is a tension between _maintainability_ (amount of work to keep the formatting correct, accommodation of contributors) and _readability_ (effort required to understand the code while updating or reviewing). Does that sum it up?

From a maintainability perspective, here's what I _don't_ like about our current standard (with things aligned), that I think @ryelle's suggestion would address:

* I am currently manually lining some things up by typing spaces. As far as I know, my IDE can't align things for me in all the situations our standard calls for.
* When a new line is added that's longer than the others, all the other lines in the group have to be adjusted, which either creates extra noise in a commit, or requires a separate whitespace commit.
* Outside contributors usually don't understand or follow the standard, which means extra cleanup for us (that is unrelated to the code quality or functionality) before a patch can be merged.

I don't personally find one way significantly more readable than the other between aligning and not aligning, but I guess it's fairly subjective. I do agree that readability is important, especially when it comes to working with code I didn't write.

For me, the most important consideration is how much time and mental overhead we're spending manually tweaking the formatting of our code, which is not high impact work. Linting tools can alleviate this overhead, especially when they can fix things automatically. So, I would rather we either write the custom linting rules to automatically align things, or go with the Core standard.

**Comment by ryelle** [comment]
> What I perceive here is a tension between maintainability (amount of work to keep the formatting correct, accommodation of contributors) and readability (effort required to understand the code while updating or reviewing). 

I think we've got an additional tension between what _is_ readable. I disagree that the current spacing is more readable, I find it hard to bounce my eyes back and forth across the open space, I have to make sure I'm reading the right line for the import I want. And for updating, any time I want to change an import, I need to change every other line so it lines up. 

> For me, the most important consideration is how much time and mental overhead we're spending manually tweaking the formatting of our code, which is not high impact work. 

I have thought about code style more in the last 2-3 weeks than in a while, so I would love to go back to being able to automate this :)

**Comment by iandunn** [comment]
Those are all good points. The new standard won't be best for me personally, but it sounds like it'll be best for the team collectively, so +1
