### ISSUE TITLE
Versioned Composer dependencies add unnecessary maintenance burden

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#159]
Continuing discussion from https://github.com/WordPress/wordcamp.org/pull/152#discussion_r303564592 so that it doesn't get lost in a closed PR.

We need to version things that run on production, like `league/oauth2-client`, but the plugins/themes are just dev dependencies, and production uses `svn:externals`.

If we version the dev dependencies, then we have to update the version number in 4 places instead of just 1. Since non-committers don't need it to match exactly, and it's running the latest 99% of the time, can we just setup Composer dev dependencies to pull `latest.zip` or `trunk` instead of a specific SVN tag?

**Comment by coreymckrill** [comment]
Works for me.

**Comment by coreymckrill** [comment]
Thinking about this a bit more. Having the plugins and themes as dev dependencies also kind of screws things up for those of us who have the svn externals checked out. We need to run `composer install --no-dev` so that the externals don't get overwritten by the wpackagist versions of plugins and themes, but then it skips actual development tools like phpcs.

What if we added a second composer.json file just for the plugins and themes (and used `latest` instead of version numbers)? We could either place it in `wp-content` and ignore it on the svn side, or we could keep it in the `.docker` folder and have it get copied over during docker provisioning.

**Comment by iandunn** [comment]
That's a good point. If it's only used by Docker installs, then putting it in `.docker` and copying feels more appropriate to me.
