### ISSUE TITLE
Blocks: Toggle descriptions should update to reflect state

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#179]
There doesn't seem to be explicit documentation on this, but [the ToggleControl example](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/toggle-control) shows changing help text depending on the state of the selection. It's a nice way to make it clear what "on" means in a toggle.

For example, in the gallery block:

| Crop toggle off | Crop toggle on |
| --------------- | -------------- |
| <img src="https://user-images.githubusercontent.com/541093/61984433-5bd21b80-afd2-11e9-9b1f-ac62b54bfb61.png" /> | <img src="https://user-images.githubusercontent.com/541093/61984434-5bd21b80-afd2-11e9-954a-4eafe0a6e483.png" /> |

**Comment by iandunn** [comment]
I'd personally still find it confusing, because I wouldn't feel confident that it's describing _the current state_ rather than _what will happen if I click on it_.

Having said that, I agree that we should be consistent w/ Core on this, to at least mitigate the inherent confusion introduced by using a non-standard UI element.

If we want to improve on it, we could make the descriptions more explicit: `Thumbnails are currently being cropped to align` / `Thumbnails are not currently being cropped` (there's probably better ways to phrase that, but that's the gist)
