### ISSUE TITLE
Block controls & content pattern

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#183]
I've always found the `block-controls` & `block-content` files a bit confusing, partially because the names are so visually similar, but mostly because it's not immediately obvious what they each do, and what the distinction is between the two.

It seems like it's a variation on [the container / branch / view pattern](https://lucasmreis.github.io/blog/simple-react-patterns/), so standardizing on those names might be more descriptive. There may be some other names that make more sense in the context of blocks, though. 

`content` is fairly descriptive, but `controls` doesn't feel very obvious to me. I guess it is the correct term, though, since [it's used in Gutenberg itself](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/block-controls-toolbar-and-sidebar/). It may be helpful to split it into the toolbar and sidebar, or something, though?

Maybe the real issue is just that I need to get used to the naming conventions in G? Opening an issue in case others have had similar or related problems, though.

**Comment by ryelle** [comment]
`BlockControls` is a thing in Gutenberg, but it actually applies just to the Toolbar area of the block, not the content itself. The content of the block itself is usually just output in the edit component, there isn't an abstraction/child component there - so if we wanted to match GB, we would essentially dissolve each `block-controls` file.

It makes sense to me to keep the `block-content` file as a separate component, at least in each block – but maybe rename it to just `content`? Or `[content-type]-list`, to be really clear (`organizers-list.js`, `speakers-list.js`, etc).

Generally files are named after the component they export, or in the case of `folder/index.js`, the folder name would match the component in `index.js`, so we'll also want to update the component names in these files too.

`content-select.js` & `inspector-controls.js` give me pause but they're pretty descriptive so I think they're fine.

As for components, I touched on this in [the classnames issue](https://github.com/WordPress/wordcamp.org/issues/184), but for the `block-controls` folder, I'd rename it. Since it only exports the placeholder, we could call it `placeholder`. As for `block-content`, maybe we can merge it into the post-list folder as they're all "post content related".

**Comment by iandunn** [comment]
> The content of the block itself is usually just output in the edit component... so if we wanted to match GB, we would essentially dissolve each block-controls file.

I would guess that's because most of the Core blocks are simpler than ours. 

> It makes sense to me to keep the block-content file as a separate component,

💯 

> maybe rename it to just content

I like that idea, `block` is kind of redundant, and I think removing the extraneous info would help me parse the distinction between it and `controls` faster.

I have a slight preference for keeping the name consistent between blocks, rather than `organizers-list`, but don't feel strongly.

I don't have a preference on the other suggestions.

**Comment by coreymckrill** [comment]
+1 for getting rid of the redundant `block` part from names

Also +1 for being consistent between blocks, rather than having `organizers-`, `sessions-` etc as part of the naming convention. I think the same redundancy argument applies here.

The original reasoning for the `block-controls` name was that it was buttons, selects, toolbars, etc. that are in the block itself, rather than in the sidebar, and affect the content, but are not part of the content. I think changing it to `placeholder` or something else descriptive of that piece of the UI is a good idea. And then the logic around the placeholder's parameters, labels, etc. could be moved to the `edit` file.

I would prefer to keep the `content` files with their respective blocks, rather than moving them over to the `post-list` component. I think components should contain as little logic about specific blocks as possible.

**Comment by ryelle** [comment]
> I would prefer to keep the content files with their respective blocks, rather than moving them over to the post-list component.

That's not what I was suggesting, just confusing names -- I meant moving the `components/block-content/*` files.

> Also +1 for being consistent between blocks, rather than having organizers-, sessions- etc as part of the naming convention. I think the same redundancy argument applies here.

Hm, so every component would just be called `Content`? I liked the idea of each being `<OrganizersList />`, `<SpeakersList />` etc - it's more descriptive of what the component is.

**Comment by iandunn** [comment]
> Hm, so every component would just be called Content? I liked the idea of each being <OrganizersList />, <SpeakersList /> etc - it's more descriptive of what the component is.

That's a good point. When looking at a folder, `content.js` seems fine, because the `speaker` context is obvious. When buried in the middle of a file, though, the context isn't as immediate, and `<SpeakerConent />` does feel more appropriate.

...but then the contention is to name the file the same as the component. So, I'd lean towards naming the file `speaker-content.js`.

**Comment by coreymckrill** [comment]
> That's not what I was suggesting, just confusing names -- I meant moving the components/block-content/* files.

Ah gotcha. Sounds good to me.

> I liked the idea of each being `<OrganizersList />`, `<SpeakersList />` etc - it's more descriptive of what the component is.
 
> When buried in the middle of a file, though, the context isn't as immediate, and `<SpeakerConent />` does feel more appropriate.

Alright, y'all have convinced me. But for consistency should we rename the other block components as well? `<SpeakerContent>`, `<SpeakerPlaceholder>`, `<SpeakerSelect>`, `<SpeakerInspectorControls>`?

**Comment by ryelle** [comment]
Can I convince you both of `SpeakerList` etc, instead of `SpeakerContent`? Just to be even more explicit that this is a list - content is kind of like meta, a word that just means "stuff" :)

- `<SpeakerPlaceholder>`  – I don't think there's a placeholder per block, so we wouldn't need that (the idea [above](https://github.com/WordPress/wordcamp.org/issues/183#issuecomment-516162262) is that each block's `BlockControls` would move into the `Edit` component)
- `<SpeakerSelect>` – Sure
- `<SpeakerInspectorControls>` – This one I think is fine as InspectorControls, since that is actually a descriptive name, but I'll leave that up to you all.

**Comment by iandunn** [comment]
> SpeakerList etc, instead of SpeakerContent?

I'm fine either way. I kinda connect `Content` to `post_content`, which feels appropriate-ish here, but I definitely see your point about it being such a generic term.

`List` might not work for all blocks, e.g., Schedule, but maybe for that we'd have something different, like `ScheduleGrid` or something.

**Comment by coreymckrill** [comment]
+1 from me as well, I'm fine either way. Let's do it.
