### ISSUE TITLE
Day of Event Template: Test with all themes

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#206]
Our supported themes are:

- [x] CampSite 2017
- [x] Twenty Thirteen
- [x] Twenty Sixteen
- [x] Twenty Seventeen
- [x] Twenty Nineteen
- [x] Twenty Twenty
- [x] WordCamp Base

---

The rest we don't test with, but will fix issues on

- Twenty Ten
- Twenty Eleven
- Twenty Twelve
- Twenty Fourteen
- Twenty Fifteen
- WordCamp Base Redux

**Comment by iandunn** [comment]
I think we should _support_ all of the themes that we have installed, but in hindsight I don't think we need to _test_ this in all of the themes, since that feels like overkill.

The ones that you bolded seem like good ones, and also `WordCamp Base` because it still gets used a decent amount.

The same goes for #205 

As an aside: we might want to disable `WordCamp Base Redux` for new sites, since it's really just `_s`, and `CampSite 2017` should serve the same use case (and do it better).

**Comment by ryelle** [comment]
> I think we should support all of the themes that we have installed, but in hindsight I don't think we need to test this in all of the themes, since that feels like overkill.

What would support mean, if we don't test this on all themes?

> As an aside: we might want to disable WordCamp Base Redux for new sites, since it's really just _s, and CampSite 2017 should serve the same use case (and do it better).

Maybe we should open an issue for that?

**Comment by iandunn** [comment]
> What would support mean, if we don't test this on all themes?

I think it'd mean that _if_ somebody opens a bug report, we'd fix it. 

When it comes to testing, we always have to strike a balance between coverage and time cost. I don't think it's worth it to have 100% coverage in this case, since we can be 90% confident that it's working by just getting 30% coverage, and we'll save ourselves several hours that way. That extra 10% of confidence doesn't seem worth the extra hours to me.

_If_ something slips though b/c we didn't have 100% coverage, though, then we can always fix it.

> Maybe we should open an issue for that?

It wouldn't hurt, but it's also not a priority IMO. There are thousands of imperfections and small improvements like that, and even if we opened an issue every time we encountered one, we wouldn't have the time to fix them; or at least, I don't think we should _waste the time_ fixing them, since we'd be losing the opportunity to spend that time on something that'll have a much bigger impact for the community.

It's a totally subjective thing, though, I do open issues which I see months later and think that it wasn't worth opening 🤷‍♂
