### ISSUE TITLE
Sessions: Start times are not saved with the correct timezone

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#226]
Currently we jump through some hoops to get the correct timezone:

https://github.com/WordPress/wordcamp.org/blob/cb99e19/public_html/wp-content/mu-plugins/theme-templates/templates/day-of-event/src/components/schedule.js#L42-L62

That's overly complicated, and I don't think it always works correctly, depending on which time zone is set.

We can simplify it to just using `gmdate()`, like the Schedule block does:

https://github.com/WordPress/wordcamp.org/blob/add/schedule-block/public_html/wp-content/mu-plugins/blocks/source/blocks/schedule/schedule-grid.js#L371

Because the value is already in the local timezone, there's no need to convert it. `gmdate()` will leave it the way it should be.

**Comment by coreymckrill** [comment]
Not sure if this is relevant, since you're talking about JS, but there is a PHP timezone function coming to WP in 5.3:

https://core.trac.wordpress.org/changeset/45853

**Comment by ryelle** [comment]
Well, this was   ⤵️🕳 

We currently save `_wcpt_session_time` using `strtotime` patching together the separate fields for date & time, which seems to technically save the value as that datetime UTC, regardless of the site's timezone. So if you have a site in EST, and you save a session for March 1st at 4pm, it will _actually_  save it as "March 1st 2020 16:00 **UTC**" (but as a unix timestamp), which is not actually when that talk is. In most places we don't care, because php's `date` also assumed UTC, but once we want to start working with this in JS, we need to care about timezones again.

_you can also see the issue if you switch `date` to the timezone-aware `wp_date` [on this line.](https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/wc-post-types/wc-post-types.php#L2047)_

This is especially a problem for the live schedule, because we need to test against `Date.now()` (or `new Date()`), which use the real current timestamp. So a talk that's on at 4pm EST would be "on now" at 4pm UTC. And all that is why we need to "account" for the site timezone here:

https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/mu-plugins/blocks/source/blocks/live-schedule/data/index.js#L52

Because that corrects the UTC-saved date into the expected, that time in the site's timezone (so a site set to EST is corrected).

So… we should probably think about updating how we save session dates to use the correct timestamp, that correctly reflects the site's timezone, but I have no idea how much else that would impact, or how to handle back-compat…?

**Comment by ryelle** [comment]
Hm… this is actually going to affect #303 too, since the datepicker localizes the date to the client timezone (in almost all cases that's fine, someone entering the session content is _probably_ in the same timezone as the camp, the regional camps are outliers, but it should get documented). So a session that's set to begin at 1pm appears to begin at 9am for me:

![Screen Shot 2020-01-13 at 5 58 27 PM](https://user-images.githubusercontent.com/541093/72299268-51faae00-362e-11ea-9fd9-c0636c2624b8.png)

**Comment by iandunn** [comment]
If we make this change, will we need to update all the PHP code that currently touches `_wcpt_session_time` in a way where the timezone matters? 

IIRC there's some code beyond wordcamp.org that would be affected, like make.w.org/community/events, and api.w.org/events.

If those aren't accounted for, a change here could cause bugs in the Events Widget and other API clients, like official and unofficial WordCamp mobile apps.

xref https://meta.trac.wordpress.org/ticket/4480

If doing this would require changing all that PHP code, then it might be easier to just accounts for `tzOffset` in the (currently) small amount of JS code?

If we don't do this, though, it'd be good to better document the technical debt that exists here.

**Comment by ryelle** [comment]
> If we make this change, will we need to update all the PHP code that currently touches _wcpt_session_time in a way where the timezone matters?

Yeah, and I'll figure out the extent of what's needed today.

> IIRC there's some code beyond wordcamp.org that would be affected, like make.w.org/community/events, and api.w.org/events.

I would _only_ touch the session times for WordCamps, which I believe is only used "internally", but part of my investigation today will be to check that assumption.

> If doing this would require changing all that PHP code, then it might be easier to just accounts for tzOffset in the (currently) small amount of JS code?

If this were never going to be a problem again I'd agree with you, but even since this issue started (in the PWA's schedule block), it's also discovered to be a problem for gutenberg-ifying the sessions CPT… and it's not like we're going to stop writing JS. I'm sure you're running into it in the schedule block too.

In any case, I'll update here later with what changes we'd need to make and what a plan could be.

**Comment by ryelle** [comment]
So, I think [this is all the change that's needed on the PHP side of things](https://github.com/WordPress/wordcamp.org/compare/try/session-date-timezones) (the date-time sorting code in the live schedule block will also need to be updated).

Luckily the date displays were all easy to change, `wp_date` is a timezone-aware replacement for `date`/`date_i18n`. Saving the date is also an easy switch, `date_create` + `wp_timezone` ensures that the unix timestamp we generate is actually the real session start time.

Of course, if I merge this branch as-is, everyone's sessions will be incorrect, so… how do we progress here?

I have a wp-cli script drafted which can loop through all sites, get all sessions, and convert the `_wcpt_session_time` to the site's timezone (if one is set, otherwise it skips the site). It currently does not _save_ this new value; that's where I'm looking for input.

- I'm going to update meta `_wcpt_session_time` with the new timestamp value
- But save the old UTC-time timestamp in another meta value (just in case, we can revert back to this with another script— should I pre-write this too?)
- Once a site is processed, it should get flagged or `add_site_meta`'d so that we don't try to process a site twice

This has the potential for being a destructive script, since it changes pretty important data — aside from the obvious "be careful", anything in particular I should know about writing a script like this? I'll of course have it reviewed before running it 🙂

**Comment by coreymckrill** [comment]
I think saving the old timestamp to a separate meta value is a good idea. Would a separate "flag" value be necessary, since a processed site will have the backup values?

I think it would also be good to enable the script to only run on a specific site ID, or array of IDs. That way we can test some specific sites that have a lot of sessions and are in a timezone not close to UTC, before running it for all of them.

Pre-emptively writing the restore script also seems like a good idea.

**Comment by ryelle** [comment]
> Would a separate "flag" value be necessary, since a processed site will have the backup values?

I think so, since it would be on a site level — if a site is flagged, we wouldn't even bother querying for sessions, we can just move on to the next site. But checking for the backup values will be a good way to not double-calculate the timestamp, so I think both are useful.

> enable the script to only run on a specific site ID, or array of IDs.

Good idea. I've got it running on a subset right now but not using specific IDs, but then we can set it to run just on our test sites at first.

> Pre-emptively writing the restore script also seems like a good idea.

👍

**Comment by ryelle** [comment]
I've committed my scripts to the bin repo, both the fixer and a reverter. They're in `bin/wp-cli/single-use/wc-post-types`. I've only tested them on the docker env, ~will give it a shot on a testing site on my sandbox tomorrow.~

Actually switching up my focus for the day, so there's more time for teammate feedback :)

**Comment by iandunn** [comment]
Should we make similar changes in other wordcamp.org code that stores timestamps (even if it's just storing a date, b/c that could change if the TZ does)? 

That'd be out of scope for this ticket, but it'd be good to open a new one to track that.

**Comment by ryelle** [comment]
Yes, it would make sense to open a new issue to track other dates.
