### ISSUE TITLE
Disable `brace-style`, `semi`, `arrow-parens` to improve readability

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#231]
I've run into a few places where the default eslint rules feel like they make the code less readable to me:

### `arrow-parens`

Desired:

`data-wordcamp-schedule-session-tracks={ assignedTracks && assignedTracks.map( track => track.slug ) }`

Required: 

`data-wordcamp-schedule-session-tracks={ assignedTracks && assignedTracks.map( ( track ) => track.slug ) }`

The extra parenthesis are not required for transpilation when there's only a single parameter, and I don't see any benefit to adding them. If they are added, though, it feels like the line is more difficult to read, because I have to mentally remove the extra characters before I can see the essential information.

### `brace-style` / `semi` / `arrow-parens`

Desired: 

`onChange={ isChecked => { setAttributes( isChecked ) } }`

Required: 

```
onChange={ ( isChecked ) => {
	setAttributes( isChecked );
} }
```

The first one feels easier scan/read to me, and keeps the code cleaner, since there're often many of those in an element, and having 3 lines for each would be onerous to parse visually:

```js
<ToggleControl
	label={ __( 'Display as Dropdown' ) }
	checked={ displayAsDropdown }
	onChange={ ( isChecked ) => {
		setAttributes( isChecked );
	} }
	onClick={ ( foo ) => {
		setFoo( foo );
	} }
	onError={ ( bar ) => {
		error( bar );
	} }
/>
```

Thoughts?

**Comment by ryelle** [comment]
I'd prefer to keep `arrow-parens`, it does have a use- from the [eslint rule description,](https://eslint.org/docs/rules/arrow-parens) "Following this style will help you find arrow functions `=>` which may be mistakenly included in a condition when a comparison such as `>=` was the intent."

Regarding the second example, you don't need the braces: It can be `onChange={ ( isChecked ) => setAttributes( isChecked ) }`, so your longer example can be

```js
<ToggleControl
	label={ __( 'Display as Dropdown' ) }
	checked={ displayAsDropdown }
	onChange={ ( isChecked ) => setAttributes( isChecked ) }
	onClick={ ( foo ) =>  setFoo( foo ) }
	onError={ ( bar ) => error( bar ) }
/>
```

So IMO these rules don't need to change, since they still serve their purpose for the rest of the code.

**Comment by coreymckrill** [comment]
I agree with @ryelle, I think the defaults here are already the best options.

**Comment by iandunn** [comment]
👍
