### ISSUE TITLE
Unmodular style.css files are difficult to work with

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#232]
For example:

https://github.com/WordPress/wordcamp.org/blob/62d83c4/public_html/wp-content/mu-plugins/blocks/source/blocks/schedule/style.scss

That file has styles for the `ScheduleGrid`, `Sessions`, `Session`, and `InspectorControls` components, making it 300 lines long, and it will only get longer before the block is done. The styles are mostly unrelated to - and independent of - each other. We keep the JavaScript code for those components separate, based on the philosophy that componentization makes code simpler to understand, test, and maintain, so I think it makes sense to do that with CSS as well.

I'd like to separate those styles into `schedule-grid.scss`, `sessions.scss`, etc.

What do y'all think?

**Comment by ryelle** [comment]
If you've got multiple components + styles, they should be broken into their own folders, for example, [`inspector-controls` is a folder](https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/mu-plugins/blocks/source/components/image) in `components/image`, with an `index.js` & `style.scss` "scoped" to that component.

So, rather than having

```
- index.js
- schedule-grid.scss
- schedule-grid.js
- style.scss
- …etc
```

It should be

```
- index.js
- style.scss
- schedule-grid/
    - index.js
    - style.scss
- sessions/
    - index.js
    - session.js
    - style.scss
- …etc
```

**Comment by iandunn** [comment]
Ah, that makes sense, I'll play around with that, thanks!
