### ISSUE TITLE
Track names not visible in mobile view

### ISSUE THREAD

**Issue by markhowellsmead** [WordPress/wordcamp.org#238]
I received feedback from WordCamp Zurich this weekend that the track names are missing in the mobile view. We worked around it using CSS pseudo classes but it would be good if we could get a solution into the standard tech. - hopefully in a new Schedule block for Gutenberg.

**Comment by ryelle** [comment]
Bringing this in from slack, the issue for the shortcode is a bug– it should display above each session title, but a recent change broke this.

Should be:

<img width="436" alt="Screen Shot 2019-09-16 at 10 48 26 AM" src="https://user-images.githubusercontent.com/541093/64968076-8ff9e800-d86f-11e9-90b1-df7f850c0862.png">

The code that broke this:

https://github.com/WordPress/wordcamp.org/blob/8839c5af0b72792a9fb05d1443cb0af9d34a4dd0/public_html/wp-content/plugins/wc-post-types/css/shortcodes.css#L9-L15

**Comment by markhowellsmead** [comment]
@ryelle Perhaps switch over to using `:after` instead of `:before`?

**Comment by coreymckrill** [comment]
Possibly related: https://meta.trac.wordpress.org/ticket/3044

**Comment by iandunn** [comment]
IIRC that may have been a known limitation of the way that the shortcode was made responsive, since it was originally built many years before RWD was common, and we needed to maintain back-compat when making it responsive.

Either way though, it doesn't seem worth fixing IMO, since we'll be deprecating the shortcode soon in favor of the block that's in development.

**Comment by ryelle** [comment]
@coreymckrill It isn't related to that issue, this was a bug that I caused with the favorite button refactor. @iandunn Since I caused it recently, I think it's worth fixing. Especially given the updated schedule block timeline. (I think the ticket Corey referenced will be fixed with the new markup, though)

In any case, the PR is up #240 🙂
