### ISSUE TITLE
End support for WordCamp via WordPress.org meta network?

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#278]
The [Meta SVN repository](http://meta.svn.wordpress.org/sites/trunk/wordpress.org/) for wordcamp.org is no longer being updated.  Should the option to develop wordcamp.org via the VVV and the WordPress.org meta network be removed from the Setup section of the [readme.md](https://github.com/WordPress/wordcamp.org/blob/production/readme.md) file?

**Comment by coreymckrill** [comment]
There's [an open issue](https://github.com/WordPress/meta-environment/issues/144) to update the Meta Environment to use this GitHub repo instead of meta.svn.

**Comment by tomjn** [comment]
Because of the customised mappings and hardcoded values this may be difficult if not impossible to do.

The fundamental problem is that there is unnecessary ultra tight coupling with WP Env. This prevents non-WP Env environments working correctly. This doesn't just impact VVV but anybody who can't run docker, and anybody who wants any other kind of local environment, e.g. raspberry PI's, staging servers, or competitors.

**Comment by timiwahalahti** [comment]
Looks like this was done in https://github.com/WordPress/wordcamp.org/commit/d4c538cf7363fecf2c3d6282c214a87ecb77fa83
