### ISSUE TITLE
Add AV wrangler name and username to API

### ISSUE THREAD

**Issue by ePascalC** [WordPress/wordcamp.org#302]
As WordPress.tv moderators we are doing regular reach outs to closed WordCamps. What we get in the API is the name and username of the lead organizer (e.g. https://central.wordcamp.org/wp-json/wp/v2/wordcamps?per_page=1&orderby=modified&page=1), but of course we would prefer to talk directly to the AV wrangler. That field is in most cases already filled in the backend but not yet exposed.
As per slack discussion (starting https://wordpress.slack.com/archives/C08M59V3P/p1576778836003700), please expose w.org username and full name of the AV wrangler in the API.

**Comment by ePascalC** [comment]
When implemented, https://central.wordcamp.org/wp-json/wp/v2/wordcamps/3087353 should show an AV name

**Comment by coreymckrill** [comment]
There aren't currently fields for the usernames of other organizers besides the lead. Only name and email address, and we obviously can't expose the email address in the API.

If we are going to expose the A/V organizer's name in the API, we should expose the other organizer roles as well, for consistency.

**Comment by ePascalC** [comment]
As the organizer name is already exposed, I would indeed love to see also the name of the AV wrangler so, from WordPress.tv, we can reach out directly to the correct person for discussion on the videos. Even with just the name, we normally find the person on slack or in a different way.

**Comment by timiwahalahti** [comment]
> If we are going to expose the A/V organizer's name in the API, we should expose the other organizer roles as well, for consistency.

I do get the point and agree with the consistency. Nevertheless, something is nagging on the back of my head, saying that is exposing all organiser roles too much? eg company following the endpoint for new WordCamps, they see sponsor/speaker wrangler's name there and contact directly after finding them somewhere instead of the form on the website or general email address. Or maybe I'm just overthinking scenarios...

In any case, @ePascalC is still something WordPress.tv would like to get from API?

**Comment by ePascalC** [comment]
@timiwahalahti I don't remember what fields were available in the backend in 2019, but for sure there was global lead and AV. Maybe there are more (now).
For WPTV, it would still be useful. If no videos arrive OR if we want to reach out before the WordCamp starts, it would be useful, yes.
