### ISSUE TITLE
Speaker Feedback: Questions for feedback

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#335]
Currently in the proposal:

> Three text area questions in the keep/tweak/delete format – these still need to be defined (and can be iterated upon after launch), but here is an example set:
> - What’s one good thing you’d keep in this session?
> - What’s one thing you’d tweak to improve the session?
> - What’s one unhelpful thing you’d delete from the session?

Where will these questions come from? Should they be controlled somewhere in the admin, so that non-developers can update them?

**Comment by coreymckrill** [comment]
Seems like there is value in having a consistent data set, so that we can look at trends over time. So I think we should have a core set of questions that are not changeable without updating the code. But perhaps organizers could optionally add one additional question of their own?

I wouldn't want to reinvent a full-blown form builder with different question types, etc. but I could see allowing a limited set of additional questions that are all just free form text fields.

**Comment by ryelle** [comment]
> So I think we should have a core set of questions that are not changeable without updating the code.

Well, we have the required questions (star rating & first question, so "What’s one good thing you’d keep in this session?"), so those would probably be fixed, with the others changeable. I'm not sure if the freeform text questions would be as helpful for "trends over time," but that's a good point.

>  But perhaps organizers could optionally add one additional question of their own?

Hm, I wasn't thinking on a per-camp basis, but that could be a nice future enhancement. I was thinking this would live in central.wc.org or a network admin screen and control all questions, so that trusted deputies could make wording changes without calling on a developer.

> I wouldn't want to reinvent a full-blown form builder with different question types, etc. but I could see allowing a limited set of additional questions that are all just free form text fields.

Oh yeah, that's definitely what I meant— like, 3 inputs with the question text and that's it.

**Comment by coreymckrill** [comment]
The other consideration with whether or not to hard-code the questions is translatability. If the questions are going to come from a central source, but still be translated into the locale of the WordCamp site, they probably need to be hard coded so that they can be wrapped in gettext calls and imported into the WordCamp translation project.

**Comment by ryelle** [comment]
Good point 👍  sounds like hardcoded is definitely the way to go, especially for this iteration.

**Comment by coreymckrill** [comment]
Hard-coded questions have now been implemented here:
https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/wordcamp-speaker-feedback/includes/comment-meta.php#L269-L301

Can this issue be closed?

**Comment by ryelle** [comment]
Yep! I think that answers the issue here.
