### ISSUE TITLE
Speaker Feedback: Track "helpfulness" of feedback

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#342]
> We can add a “Was this feedback useful?” question for the speaker to submit as a way of tracking the value of the feedback.

Should this be per comment? Could use the same pattern as moderation?

![Speaker Feedback-help](https://user-images.githubusercontent.com/541093/73208354-520daa00-4114-11ea-8db1-7804c8522e5e.png)

Or should this be a specific question somewhere on the page?

**Comment by coreymckrill** [comment]
> Should this be per comment? ... Or should this be a specific question somewhere on the page?

I think it depends on whether we want to assess the helpfulness of the speaker feedback functionality as a whole, or track the amount of feedback that is considered helpful vs unhelpful.

Going the more granular route seems best to me, but then I guess the risk is that speakers wouldn't take the time to rate the helpfulness of each individual comment. If they just marked the "unhelpful" ones for example, that might skew our data.

**Comment by coreymckrill** [comment]
Maybe instead of having two options, we just have a "Helpful" button. Speakers would only click the button for things that were truly helpful to them. Then we could measure the _percentage_ of feedback that was deemed helpful on each individual session.

I've seen similar schemes on things like Yelp reviews. You can mark something as "Cool" or "Helpful", but there aren't any negative options.

**Comment by ryelle** [comment]
> Then we could measure the percentage of feedback that was deemed helpful on each individual session.

I like that idea. There's probably a lot of overlap between actively unhelpful comments & spam (or otherwise moderated-away content).

Would we also want to track percentage of moderated comments, to keep an eye on negativity? that might need a separate status (since they'd be trashed now).

**Comment by coreymckrill** [comment]
> Would we also want to track percentage of moderated comments, to keep an eye on negativity? that might need a separate status (since they'd be trashed now).

If we wanted to track comments that aren't spam, but still aren't worth showing to speakers, then a separate status would probably be the way to go. But I'm not sure I understand what we'd gain by tracking that specifically.

**Comment by ryelle** [comment]
Whether people are being jerks, really… 

Is the "helpful" button only for the speaker(s)? I'm wondering if it would only be on the frontend view we're talking about in #347, or also in the wp-admin list.

**Comment by coreymckrill** [comment]
> Is the "helpful" button only for the speaker(s)?

I was thinking that it was. I think it would be weird if the organizers could mark which feedback was "helpful" for the speakers.

**Comment by coreymckrill** [comment]
> Whether people are being jerks, really…

So, like to track if specific people are consistently jerks, or more just what percentage of submitted feedback is mean-spirited garbage that isn't worth passing on to speakers?

**Comment by ryelle** [comment]
Initially I was thinking the latter, but the former might be good for some audit-log style tracking for any possible CoC violations.

**Comment by coreymckrill** [comment]
Ok, I've split out this idea of having a new comment status into its own issue: https://github.com/WordPress/wordcamp.org/issues/414

**Comment by coreymckrill** [comment]
Since the button to toggle "Helpful" for a feedback comment will be [on the front end](https://github.com/WordPress/wordcamp.org/issues/347), that means we'll probably need to be able to do that toggle action via a REST API call. Which means extending our current REST controller to also have `update_item` functionality.

We'll also have to store a value for comments that are "helpful", most likely a boolean as comment meta. One potential twist, though, is that we wouldn't want the "helpful" value to be settable when a new feedback comment is created, only when it's updated later. And vice versa, we wouldn't want the rating or answers to questions to be changeable during an update, only when the feedback is first created. So I'm thinking we'll need to add the concept of `context` to our meta fields. Some would have a `create` context and some (one at this point) would have an `update` context.

Thoughts @ryelle? Am I overthinking this? Anything I'm missing?

**Comment by ryelle** [comment]
Maybe `POST` to `/feedback` could do the create, while `POST` to `/feedback/<id>` only sets a helpful value? I think the update vs create would be different callbacks, so we can do whatever we want… but I can do more thinking on this next week.

What do we do for multiple speakers on a session? This is probably a pretty edge-case scenario, but what if they disagree about helpfulness?

**Comment by coreymckrill** [comment]
> Maybe POST to /feedback could do the create, while POST to /feedback/<id> only sets a helpful value?

Yep, this is what I'm thinking too. What I'm getting at is that the set of valid meta values from our `get_schema` function would be different between those two endpoints.

> What do we do for multiple speakers on a session? This is probably a pretty edge-case scenario, but what if they disagree about helpfulness?

Oh interesting. This makes me wonder if "helpfulness" should be a comment meta value, or a _user_ meta value.

I guess it depends on what we want to do with the data. If we want to measure what percentage of comments are deemed "helpful" (i.e. this data is mostly for us), comment meta is probably better. But if this is mostly a way for speakers to filter their feedback, user meta would probably be easiest.

I've been assuming it's the former. I actually don't think it would be too much of an issue, even in cases of disagreement. The speakers would probably mostly settle on either an inclusive or exclusive strategy for determining what gets marked as "helpful".

**Comment by ryelle** [comment]
@coreymckrill Can this issue be closed since #420 was merged, or do you think there's still something that needs to be done here? #347 covers the frontend UI, and #425 covers the issue about non-site speakers.

**Comment by coreymckrill** [comment]
I was thinking that since this is ultimately about "tracking" helpfulness, we should leave this open until we have some sort of reporting mechanism.

**Comment by ryelle** [comment]
Ah, when I wrote the issue I meant track as "keep track of, store somewhere". Are you picturing something different than the reporting in https://github.com/WordPress/wordcamp.org/issues/344?

**Comment by coreymckrill** [comment]
Ah, no, good point. I'll just add it as another bullet point there.
