### ISSUE TITLE
Update webpack.config.js to have only one defination of `NODE_ENV`

### ISSUE THREAD

**Issue by vedanshujain** [WordPress/wordcamp.org#37]
See https://github.com/WordPress/wordcamp.org/pull/33#discussion_r267140626

Ideally this should be a minor change, but it is blocked on how we generate build files. Right now we do it on our local environment, but ideally it should be done on sandbox with `NODE_ENV` variable set.

**Comment by iandunn** [comment]
Fixed in 508984cce4e5a65bc65f907ad369ee7e64928f9c.

I realized we couldn't just reuse `NODE_ENV` for the `mode` param, since webpack requires it to one of a few specific values, so I just added a comment to that effect.

I also found a better way to setup the source maps, so I didn't need to duplicate the logic that checks the `NODE_ENV` value.
