### ISSUE TITLE
Speaker Feedback: Network enable/disable doesn't handle the activation/deactivation hooks correctly

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#370]
When the activation state of this plugin is changed network-wide, the related activation/deactivation routines that are registered do not appear to be firing, because the Leave Feedback page is not created upon activation, and it's not deleted upon deactivation.

This was partially addressed [here](https://github.com/WordPress/wordcamp.org/pull/357/commits/b999a6a5be08a32bcaae1dbd31f0c9807274c642) by also checking during `init` and creating the page if necessary, but it doesn't address the deactivation part.

I have a theory (untested, just wanted to get this idea out in an issue) that these routines _are_ actually running, but because they're being run from the network admin, they're not running in the proper context to do what is intended.

So I think what might be needed is for the `activate` and `deactivate` callbacks to check the optional boolean parameter that's supplied during the relevant action hook that says whether or not this is a network context. If it is, the routine will need to run through a `switch_to_blog`/`restore_current_blog` loop for each site in the network in order to add/remove the feedback page and related option.

If this is the solution, the other question is, do we actually want to do that on a network with 1k+ sites? That would potentially be an intensive operation. Obviously we could skip sites with the [skip feature flag](https://github.com/WordPress/wordcamp.org/pull/363). We also wouldn't run these routines very often (`deactivate` maybe never on production).

**Comment by ryelle** [comment]
As of #363, there is a skip feature flag (but AFAIK it's not applied to any sites yet), and the page is not (only) created as part of the activation but should also be created when the site is first loaded, so that piece should still work for all sites.

The outstanding issue is rewrites— the `/session/blah/feedback` endpoint doesn't exist without flushing rewrites for the individual sites. This'll only affect sites that exist when we turn on the plugin though (new sites are created with the rewrite in place), so maybe we can just run a wp-cli to flush all existing sites.

So we'd pick a site ID as the cutoff, then…

1. Apply the skip feature flag to all older sites.
2. Network activate the plugin
3. Get a list of sites with `site_id > cutoff`, and run `wp rewrite flush --url=site…` for each; or some php script that calls `flush_rewrite_rules` in the context of each site.
