### ISSUE TITLE
In session and speaker block, select options takes long time to load

### ISSUE THREAD

**Issue by vedanshujain** [WordPress/wordcamp.org#39]
If there are posts already selected in session and speaker blocks, the selected items inside select box render sometime after actual posts content is rendered. If we already have data to render post content, we should consider using same data to display selected items in these blocks.

**Comment by coreymckrill** [comment]
Another related issue is that if you add a second instance of the block, or remove the block and re-add it, the options have to load all over again, because the data fetched from the API is only cached within the block itself. I think this would be solved by using the data store structures available in Gutenberg, but I couldn't figure out how to do it without using `withSelect`.

**Comment by coreymckrill** [comment]
Related: #69

**Comment by coreymckrill** [comment]
I believe this is resolved with #69.
