### ISSUE TITLE
Upcoming Events Widget not honoring status changes for canceled and postponed WordCamps

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/wordcamp.org#396]
**Describe the bug**

In the WordPress Events and News dashboard box, WordCamp events that have been cancelled 
 or postponed by changing the status from WordCamp Scheduled to Canceled or In Pre-Planning are still showing in the box.

**To reproduce**

1. Browse to https://central.wordcamp.org/wp-admin/ or any WordPress install with the WordPress Events and News dashboard box available
2. Change your location to Antwerp
3. You will see 
> WordCamp Antwerp, Belgium
> Antwerp, Belgium
> Friday, Mar 27, 2020

**Expected behavior**

You should not see WordCamp Anterwp 2020 since this WordCamp is In Pre-Planning.
https://central.wordcamp.org/wp-admin/post.php?post=3088765&action=edit&classic-editor

**Screenshots**

What I see when testing on https://central.wordcamp.org/wp-admin
![image](https://user-images.githubusercontent.com/3489003/77127410-52426b80-6a1a-11ea-9ef9-ca47c6fdd8a2.png)

Reported today in [Slack](https://wordpress.slack.com/archives/C037W5S7X/p1584651083185600).
![Image from iOS](https://user-images.githubusercontent.com/3489003/77127377-33dc7000-6a1a-11ea-895d-442d22fb48e0.jpg)

**System (please complete the following information):**
N/A

**Comment by ryelle** [comment]
@CdrMarks This should be fixed now, though you might still see locally cached items for another few hours. I'm going to close this issue, but feel free to re-open if you're still seeing unexpected WordCamps in the list.

**Comment by CdrMarks** [comment]
@ryelle I no longer see WordCamp Antwerp, a canceled event.

I am still seeing WordCamp Paris, a postponed event, when using Antwerp as my current location.  Paris changed status from WordCamp Scheduled to In Pre Planning on March 11.  I am still seeing their event listed as occuring in the Dashboard box on April 17.

WC Paris 2020: https://central.wordcamp.org/wp-admin/post.php?post=3095584&action=edit&classic-editor

Also, looks like I'm unable to reopen this.

**Comment by ryelle** [comment]
I've manually updated WordCamp Paris — it seems that WordCamps still need to have dates in order for them to be synced down to the API, even if they're set back into pre-planning mode. I don't think this requires a code change, since this flow is a bit of an outlier, but if you see more WordCamps like this, leave a comment here & I'll reopen the issue.

**Comment by CdrMarks** [comment]
I've reviewed the [Tracking Upcoming WordCamp](https://docs.google.com/spreadsheets/d/1XFccGP1a8kU5lw94a_yWGzVOFgk55KE3ZkQ-jMOCiBo/edit#gid=0) Google Sheet and added column L, `Upcoming Events?`, to the sheet with my findings.

**Comment by iandunn** [comment]
I'm seeing some pre-planning camps in the widget too, like Buffalo.

I'm working on some related changes, so I'll take a look.

**Comment by iandunn** [comment]
https://meta.trac.wordpress.org/changeset/9786 removes camps from the Events Widget API if they're no longer scheduled. That removed Houston, Moscow, and Detroit.

I'm also not seeing Buffalo anymore, or any of the others in the spreadsheet. That's possibly because of one of the other commits recently. 

I'll go ahead and close, but please re-open if you notice any other problems.
