### ISSUE TITLE
The list of plugins currently installed on a local environment seems to be different to 2020.our.wordcamp.org

### ISSUE THREAD

**Issue by rocket-martue** [WordPress/wordcamp.org#397]
> Hi! We (WordCamp Ogijima organizer team <@U73PBU6KB> <@U11NLBL6S>)  are trying to create a local environment for the <http://WordCamp.org|WordCamp.org> site.
> 
> <https://meta.svn.wordpress.org/sites/trunk/wordcamp.org/public_html/wp-content/plugins/>
> 
> <https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins>
> 
> Does anyone know where to find the right in the plugins currently installed on <http://WordCamp.org|WordCamp.org>?

[View in Slack](https://wordpress.slack.com/archives/C08M59V3P/p1582898747016100)

**Comment by coreymckrill** [comment]
Hi @rocket-martue 

This repository on GitHub is now the correct source of the WordCamp.org codebase, rather than meta.svn. It includes a [Docker config](https://github.com/WordPress/wordcamp.org/tree/production/.docker) that you can use to set up a local environment that is more up to date than that found on meta.svn (although it might still be a little bit outdated).

If you're trying to set up a local environment using the Meta Environment module for VVV, the WordCamp portion of that is currently not functional because of the move to GitHub. There's [a pending issue](https://github.com/WordPress/meta-environment/issues/144) to get it updated.

Closing this issue, but if you have any questions about getting the Docker environment set up, please ask in the `#meta-wordcamp` channel on WP Slack and we'll try to get them sorted out.
