### ISSUE TITLE
Speaker Feedback: Add UI for speakers to opt out of email notifications about approved feedback

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#488]
In #441 I introduced a usermeta value to check whether a speaker has opted out of email notifications before sending the email about new approved feedbacks. However, that PR didn't include any UI additions where a speaker could actually set that value.

Storing the value in usermeta means that the opt out will apply for _all_ WordCamps. This way the speaker doesn't need to re-opt out if they speak again at subsequent events.

I'm unsure where this UI addition should go, but here are a couple of rough ideas that are maybe not mutually exclusive:

* A checkbox on the front end feedback view. The speaker would need to receive at least one email notification, and then when they follow the link, they could check the box to prevent further notifications. They could also then uncheck the box later if they wanted to turn the notifications back on.
* A checkbox somewhere on the Edit Speaker screen for the Speaker post type. This would most likely be toggled by an organizer, at the request of the speaker.

**Comment by hlashbrooke** [comment]
Could we do a combination of both the options you mentioned, so that it can be managed by the speakers as well as the organisers? If only one then the front-end UI for speakers would be the priority.

If it's on the page where speakers view their feedback then the organisers could let the speakers know about it before the event so they choose to opt-out beforehand if they like.

**Comment by hlashbrooke** [comment]
In terms of a good UI, I was thinking just a button on the page for viewing feedback would be good since it would just be one click to trigger (as opposed to selecting a checkbox and then clicking submit). The button text could change depending on the action - "Click to opt-out of receiving session feedback" or "Click to opt-in to receiving session feedback"
