### ISSUE TITLE
Blocks: Abstract into parent/child classes to make code more DRY?

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#56]
It feels like Speakers/Sessions/Sponsors/Organizers share _a lot_ of code in common, with minor differences. Here's some examples of where things are very close, with with minor differences in variable names, function parameters, etc

* `includes/{type}.php`
* `view/{type}.php`
* `src/{type}/edit.js`
* `src/{type}/block-content.scss`
* `src/{type}/block-controls.js`
* `src/{type}/inspector-controls.js`
* `src/{type}/speakers-select.js`
* `src/{type}/toolbar.js`

I know we want to be careful about over-engineering things, because having a maze of abstraction layers can be worse than code duplication, but if feels like we may be erring too far to the side of duplicating right now.

What do y'all think about the above? Are there some places where it'd make sense to add an abstraction layer, and other where it makes sense to keep it the way it is?

**Comment by coreymckrill** [comment]
I'm open to seeing what you would propose specifically in terms of abstraction, but I would hesitate to abstract away any of the files you list that exist for each of the blocks. Having those files keeps the blocks flexible for future development and maintenance, where their current commonalities might diverge.

Rather than abstracting entire chunks of the file structure, I think I would prefer to abstract more pieces into shared components. That maintains a bit more flexibility, because then we have repeatable chunks that don't necessarily need to appear in the same context in every block, or the same order.

**Comment by vedanshujain** [comment]
@iandunn I also thought this while working on Sponsors block, and considered adding a component for`CustomPostType`, which will basically be a abstraction over these different blocks. However, these blocks are different enough, that it could result into abstraction maze instead of simplifying stuff. 
I agree with @coreymckrill here, I think we can put more thought into creating better shared components to keep our code DRY.

**Comment by iandunn** [comment]
👍 

That's the direction I was thinking too: more shared components that can accept props to account for minor differences, but not replacing entire files.

I definitely agree that a maze of abstractions should be avoided.

I'll work on a PR once some of the other things have settled down, in order to minimize merge conflicts.

**Comment by iandunn** [comment]
Good food for thought:

> "Duplication is far cheaper than the wrong abstraction." ([>>](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction))

hat-tip @coreymckrill

**Comment by ryelle** [comment]
At this point I think we've settled on the architecture we have, so I'm going to close this out – feel free to re-open if there's still something to discuss here.
