### ISSUE TITLE
Upcoming camps missing from Central schedule map

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#571]
https://central.wordcamp.org/schedule/

The only events showing up on the map are in 2021, even though there are 8 with the `scheduled` status now. It may have something to do with them being online events, or that could just be a coincidence.

cc september maintenance dev - @ryelle

**Comment by ryelle** [comment]
Yeah, it's because they're online events. I think that's to be expected, since virtual camps don't have a venue - so they don't have `_venue_coordinates` for the map to use.

Maybe we could update the coordinate encoding in `update_venue_address` to use the Location field if no venue address, and backfill the currently-scheduled events. Do you think that would have any unexpected consequences anywhere (like in the events widget)?

**Comment by iandunn** [comment]
Ah, yeah, good point.

That sounds like a good plan to me. What do you think about using the `Host Region` field? IIRC that's what the Official Events plugin pulls for the Events Widget.

**Comment by ryelle** [comment]
Oh nice, I see that's encoded into `_host_coordinates` for online events 👍 

I'll update the markers on central to use that if venue_* doesn't exist.
