### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by ghost** [WordPress/wordcamp.org#645]
Imported from https://meta.trac.wordpress.org/ticket/4926 
Created by [@dkarfa](https://profiles.wordpress.org/dkarfa/):

```
Uncaught Error: Call to undefined function WordCamp\Theme_Templates\is_offline() in /srv/www/wordpress-meta-environment/meta-repository/wordcamp.org/public_html/wp-content/mu-plugins/theme-templates/bootstrap.php on line 149
```

**Comment by ghost** [comment]
[Comment](https://meta.trac.wordpress.org/ticket/4926#comment:2) by slackbot:

_This ticket was mentioned in [Slack](https://make.wordpress.org/chat/) in #meta-wordcamp by iandunn. [View the logs](https://wordpress.slack.com/archives/meta-wordcamp/p1597945108040700)._

**Comment by ryelle** [comment]
This was likely due to not having the PWA plugin installed. Both the docker environment and the VVV meta-environment install the PWA plugin on provision now. I'm going to close this issue – if anyone else runs into this, check that the PWA plugin is active. If that doesn't help, you can open a new issue.
