### ISSUE TITLE
Sessions: When session is 50min, initial duration isn't saved

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordcamp.org#682]
When setting up a session, the "session length" defaults to 50min. If you change it, it will save in the `_wcpt_session_duration meta` field. If you change it back to 50min it will save. But **if you don't change it at all,** it will not save any value, leaving `_wcpt_session_duration` as `0`.

This causes a bug in the schedule block, where sessions have 0 length (16:00 - 16:00):

<img width="1204" alt="Screen Shot 2021-06-01 at 10 34 02 AM" src="https://user-images.githubusercontent.com/541093/120342128-7f003d00-c2c5-11eb-9e6e-8d5996999ac6.png">

In the above, "Are your customers…" session, this is result from an API request:

```
"meta": {
    "_wcpt_session_time": 1623160800,
    "_wcpt_session_duration": 0,
    "_wcpt_session_type": "session",
    …
},
```

Only after I changed the value on another session to 45min, saved, then changed back to 50min did it save correctly.

**Comment by iandunn** [comment]
This one has been tricky to figure out. Before #512, the Classic editor was used to create/edit sessions, and it would save all the default meta values to the DB, regardless of whether or not they were modified by the organizer. It seems like Gutenberg's default behavior is to only save them if they've been explicitly modified.

I'm guessing this was working immediately after #512, because we probably would have noticed it in testing, but it's difficult to `bisect` that far back due to PHP8 incompatibilities, etc.

I think this breaks down into three potential problems:

1. If no meta values are changes, the default values aren't saved to the DB
1. if someone changes a meta value _other than_ the duration, a duration of `0` gets saved to the DB instead of the default
1. if no duration is in the DB, the Schedule block labels the session as having `0` duration, and assigns an end time equal to the next session's start time.

Problem `3` exists because the code assumes the Classic editor behavior. If we accept that problem `1` is correct behavior now, then we could fix everything by adding a `prepare_callback` to the `_wcpt_session_duration` field in the API, with something like:

```php
return empty( $value ) ? WordCamp_Post_Types_Plugin::SESSION_DEFAULT_DURATION : $value;
```

I can't think of a valid use case for having a session set to `0` duration, so it should be fine to treat a DB value of `0` the same as not being set. That should fix it retroactively for existing sessions.

That still feels a bit hacky, though, so I'm curious if anyone has other ideas.

**Comment by coreymckrill** [comment]
Would adding a default value to the `register_post_meta` call fix it? I.e.

```php
	register_post_meta(
		'wcb_session',
		'_wcpt_session_duration',
		array(
			'type'          => 'integer',
			'show_in_rest'  => true,
			'single'        => true,
			'auth_callback' => __NAMESPACE__ . '\meta_auth_callback',
			'default'       => 50,
		)
	);
```

**Comment by iandunn** [comment]
Ah, I forgot about that! I'll test it out, thanks!
