### ISSUE TITLE
The Events and News section on the WordPress Dashboard doesn't render the date of WordCamps correctly.

### ISSUE THREAD

**Issue by huanyichuang** [WordPress/wordcamp.org#709]
**Describe the bug**

The date of WordCamp doesn't display correctly on the WordPress Admin dashboard.

**To reproduce**

1. Go to 'Dashboard'
2. See the bottom right of the page, check the 'WordPress Events and News' section.

**Expected behavior**

The correct date should be displayed (2021/12/11 - 2021/12/12)

**Screenshots**
<img width="1264" alt="截圖 2021-11-16 00 33 07" src="https://user-images.githubusercontent.com/18607348/141819947-5f1cb160-3b23-4a4b-9d39-21a5f3d2bf9b.png">

**WordCamp**

[WordCamp Taiwan 2021](https://taiwan.wordcamp.org/2021/)

**System (please complete the following information):**
 - Device: All Devices
 - OS: iOS, macOS
 - Browser Google Chrome
 - Version 95.0.4638.69

**Comment by iandunn** [comment]
Hi, I think this is an error in the translation, rather than WordCamp.org:

* https://translate.wordpress.org/projects/wp/dev/admin/zh-tw/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9144372&filters%5Btranslation_id%5D=78848419
* https://translate.wordpress.org/projects/wp/dev/admin/zh-tw/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9144375&filters%5Btranslation_id%5D=78848418

If you temporarily switch to `zh_CN`, you'll see that it's working. Here's what their version looks like:

* https://translate.wordpress.org/projects/wp/dev/admin/zh-cn/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9144375&filters%5Btranslation_id%5D=87991418
* https://translate.wordpress.org/projects/wp/dev/admin/zh-cn/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9144372&filters%5Btranslation_id%5D=87991436

You can fix it by suggesting a new translation for `zh_TW`. The PHP date format documentation may be helpful:

* https://www.php.net/manual/en/datetime.format.php

cc @alexclassroom

**Comment by alexclassroom** [comment]
@iandunn 

This bug confuses me from WordPress 5.4, because I follow the **ORIGINAL** strings and localize them by local time order.

As the previous results, it doesn't work well.

Following zh_CN and comparing with original strings, the date and time variables are changed. This is unusual.

Original: %1$s %2$d–%3$d, %4$d
Previous zh_TW translation: %4$d %1$s %2$d – %3$d (Doesn't work)
Current fixed zh_TW translation: %4$s %1$s %2$s – %3$s ($d variables are changed to $s, but work well)

Even if I can't understand what's happened, the new translations work well, If someone knows the reason, please let me know.

I fixed this issue from WordPress 5.4 to 5.8, not only 5.8.

**Comment by ryelle** [comment]
A similar issue was reported in [core, #53381](https://core.trac.wordpress.org/ticket/53381).

**Comment by iandunn** [comment]
Ah, you're right, I'd forgotten about that, thanks!
