### ISSUE TITLE
CampTix: Allow bypassing the 10 ticket per order limit with a special link?

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/wordcamp.org#740]
Sometimes companies bulk purchase WordCamp tickets for employees, and the 10 ticket per order limit means more clicking and multiple invoices to process.

Why the limit in the first place?

The reasoning is not known for sure, but it's probably related to preventing people from buying/reserving a big block of tickets and then scalping them or just not showing up, denying other people access to the event.

One solution might be to allow a WordCamp site to generate a special link that goes to the ticket order form, but without the limits (or at least with much larger limits).

**Comment by jaz-on** [comment]
Thank you @coreymckrill for opening the ticket! 👍

**Comment by jaz-on** [comment]
Up. Any news on this since last year?
As the WCEU sponsors team lead, this is a very annoying limitation.
On several sponsorship benefits, we offered our sponsors more than 10 tickets.
When sharing the coupon code with them, they need several orders to book all their tickets, which isn't convenient at all...

**Comment by timiwahalahti** [comment]
In addition to sponsor benefits, sometimes companies ask to bulk-buy tickets with invoices. In these cases coupon code for that purchase is made. Given this, I'm thinking of adding a setting for coupons to override the limit.
