### ISSUE TITLE
Remove "Needs Mentor" status

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/wordcamp.org#866]
**What we need**

"Needs Mentor" status on WordCamp Tracker to be removed.

**Issue**

Sometimes it takes time to find a Mentor, while the progress of the WordCamp planning is actually going. Hence, we don't have to have it as a status because it does not reflect the actual status of the WordCamp planning.

<img width="328" alt="Screenshot 2023-04-13 at 17 48 46" src="https://user-images.githubusercontent.com/75025757/231737087-b015873e-40a1-48dc-9c97-216086d7d1de.png">

**Comment by timiwahalahti** [comment]
Do you think we need some other way to mark the need for a mentor? Like on/off toggle. Or should the [Mentors Dashboard](https://central.wordcamp.org/wp-admin/edit.php?post_type=wordcamp&page=mentors) use the "Mentor WordPress.org User Name" field in WordCamp data to list the WordCamps needing a mentor?

**Comment by devinmaeztri** [comment]
Yes! We were thinking either banner or tags (on/off toggle) on WordCamp tracker. 

`"Mentor WordPress.org User Name" field in WordCamp data` - do you mean we have the mentor information listed here? If yes, that's actually a great idea. So we can see the Camp that has no Mentor easily. 

<img width="1107" alt="Screenshot 2023-04-19 at 20 57 26" src="https://user-images.githubusercontent.com/75025757/233098385-11c38ff4-1944-4168-956b-bf6d32bbf16a.png">

<img width="395" alt="Screenshot 2023-04-19 at 20 57 43" src="https://user-images.githubusercontent.com/75025757/233098398-92bcf3e6-d322-4a92-9787-2b751aced1eb.png">

**Comment by catederosia** [comment]
I'm here to second that we need some form of "Needs Mentor" alert to let us know what WordCamps need a mentor that is different from our current system.

Right now the alert is tied to a tracker setting that sends a single automated email. The problem is, that if we can't assign the mentor right away, we either have to leave the tracker set at "Needs Mentor" or change the tracker setting and hope we remember to assign a mentor at a later date.

We'd like to be able to move the WordCamp tracker ahead without having the "Needs Mentor" notification tied to tracker status, but in a way that continues to remind us that the event still needs a mentor.

**Comment by timiwahalahti** [comment]
Here's what I suggest:

* Remove the "Needs Mentor" status as per the original request
* The [Mentor Dashboard](https://central.wordcamp.org/wp-admin/edit.php?post_type=wordcamp&page=mentors) has the list of WordCamps that need a mentor, but not all WordCamps end in that list due to the query checking post statuses alongside mentor field on WordCamp data -> remove the status checks from the query and solely trust on "Mentor WordPress.org User Name" field being filled on the singular WordCamp details
* After that, the existing cron job alerting about WordCamps without a mentor via email ([example in HS](https://secure.helpscout.net/conversation/2304288070/162551/))should use the same list -> confirm this

Would this work?

**Comment by devinmaeztri** [comment]
That sounds good, @timiwahalahti and apologize for the delayed response!

> After that, the existing cron job alerting about WordCamps without a mentor via email ([example in HS](https://secure.helpscout.net/conversation/2304288070/162551/))should use the same list -> confirm this

Indeed, we get notifications about the Camps that need a Mentor but it does not reflect the actual status.
