### ISSUE TITLE
New Attendee Checkbox on the Ticket Registration Form

### ISSUE THREAD

**Issue by catederosia** [WordPress/wordcamp.org#875]
Add a new checkbox in the WordCamp ticket registration that asks if the person is a first-time attendee. 

- [x] #892 
- [ ] Track data based on event type
- [x] Add report

**Comment by iandunn** [comment]
That sounds good, that'll be more accurate than the bin script we have 🎉 

We may need to integrate that data into the bin script, but continue to use the current name/email matching, so that we get stats on date ranges from before this launches. That may not be worth it, though, and we could just have the current script for the dates before, and the new data for the dates after.

**Comment by iandunn** [comment]
The report was added in #935

**Comment by StevenDufresne** [comment]
Is this complete? We still have "Track data based on event type" unchecked. What is that referencing specifically?

**Comment by iandunn** [comment]
That refers to the 2nd question in https://github.com/WordPress/wordcamp.org/pull/892#issuecomment-1585154451

**Comment by iandunn** [comment]
This is the last open issue in the milestone, and most of it is done. IIRC there's been some discussion on if we should do the remaining task or not, so I think it's fine to close this now, and then open a new issue for that once the community team decides on it.
