### ISSUE TITLE
Provision Pilot Event Sites

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#885]
Pilot sites will need to use the WordCamp infrastructure because they'll use the Budget plugins, automated site provisioning, etc, but they'll also need some customizations since they're not actually WordCamps.

We could use the existing `wordcamp` post type, with a post meta field, taxonomy, etc to distinguish them from traditional camps, or create a new post type entirely. 

Since these are experiments and there are so many unknowns, I'm a little leery of creating a new CPT before we really understand what the needs will be long term. A lot of the codebase is designed to integrate with the `wordcamp` post type, and may need to be updated to work with a new one. That could introduce technical debt if we end up needing something different, etc.

On the other hand, a new post type could help isolate any changes from the `wordcamp` post type, and having a clean break between the two may help make changes to the codebase less fragile. There's also a concern around stats, since pilot events probably shouldn't be counted as WordCamps, etc.

Either way, there are hundreds of things that reference the `wordcamp` post type explicitly or implicitly, via `WCPT_POST_TYPE_ID`, `'post_type' => 'wordcamp'`, `get_wordcamp_post()` etc.

Another idea would be to create a new network inside the Multisite for these events, so that we can have different plugins network-activated, etc. That may remove the need to update some plugins, but definitely not all. 

It may require some experimentation to see which approach will fit best and be practical within the time constraints.

What do you think @StevenDufresne @ryelle @dd32 ?

Related #881 

----
 
_Update: Actionable items:_

These are interdependent with #884 

- [x] Create an additional network. 
    - [x] The README and docker conf should be updated so it can be reproduced across envs. 
- [x] Create a main `events.wordpress.org` site that'd serve as the "central" for the pilot events CPT and other management tools
    - [x] Set `BLOG_ID_CURRENT_SITE` programmatically

**Comment by iandunn** [comment]
@pkevan it'd be good to hear your thoughts on this too

**Comment by pkevan** [comment]
i'll circle back to this tomorrow when i'm traveling and have some time to look in more detail.

**Comment by pkevan** [comment]
> Another idea would be to create a new network inside the Multisite for these events, so that we can have different plugins network-activated, etc. That may remove the need to update some plugins, but definitely not all.

Given we are planning to run this via a events.wordpress.org domain it seems like this would be a good option, that way we are separating it out but could potentially re-use the existing code. 

Any alteration to this can hopefully be done via a network level code, but should it become too burdensome we could separate out too.

**Comment by ryelle** [comment]
I like the idea of a new subnetwork from a separation point of view. If we created a new sub-network, would that mean creating a new plugin to handle the Pilot Events, or letting the WordCamp post type on the new network actually mean Pilot Event? I suppose if we created a new plugin/CPT we'd still have the same issues.

What happens when this pilot leads to new event types… I guess at that point we would know more about what's specifically required for those new events, so we could create the new CPTs as needed, and deal with the `wordcamp` dependency then.

Would a new subnetwork impact reporting/management from Central?

**Comment by dd32** [comment]
> Another idea would be to create a new network inside the Multisite for these events, so that we can have different plugins network-activated, etc. That may remove the need to update some plugins, but definitely not all.

I _think_ this makes sense from a separation POV, it'll make it clear as to which "thing" the site is related to.

It may require some of the network-query queries for stats to be updated to query specifically for all blog_ids rather than just blog_ids for the current network, but that's a benefit too as it'll probably allow easier splitting of stats (ie. just query for network id 2)

I'd say let's move forward with that to start with, and if that proves not to be workable, we can combine the networks later if needed (Since it won't adjust any tables, etc)

**Comment by iandunn** [comment]
Creating an additional network WFM 👍🏻 

I'm leaning towards a separate post type as well. I was thinking it could have a dropdown for event type, so that it could support multiple, rather than having a different CPT for each type. It's not really clear yet what the types will be or how much they'll differ, though, so we probably don't need to decide that yet. We can just start w/ one and decide later on if it should be forked into multiple, or expanded to support all types.

So the actionable things for the MVP seem to be:

_[ Edit: checklist items moved to issue description so they can start being worked on ]_

Any thoughts on those? Is anything missing?

**Comment by iandunn** [comment]
These seem out of scope for the MVP, but would be nice for future iterations:

- [x] Automatic site provisioning - just like with the wordcamp post type, but the site should be created on the new network. we can just do it manually for the MVP (#901)
- [ ] Modify the admin bar/menu to make it easier for folks to understand that there are 2 networks and navigate between them. I can imagine someone going to the `Sites` page and being confused that they only see wordcamp sites, or vice versa. (#902)

**Comment by iandunn** [comment]
I think the actionable things are done now, or have been moved into more specific tickets like #886, #900, #901, etc.
