### ISSUE TITLE
Add Volunteers post type

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#887]
Related https://github.com/WordPress/wordcamp.org/issues/550

Pilot sites want to take volunteer stats into account when measuring success, so we'll need a volunteer post type for that. 

- [x] #895 
- [x] #898 
- [x] Add/update Handbook docs

**Comment by StevenDufresne** [comment]
> automatically draft volunteer posts

We save the w.org username to the volunteer post and that's all we do for tracking?

**Comment by iandunn** [comment]
I was thinking there'd be another ticket that'd focus on generating any related reports; this ticket would just be where we create the post type so that the raw data exists in the system.

**Comment by StevenDufresne** [comment]
Yep sure, just trying to understand how this ties together. Thanks.

**Comment by iandunn** [comment]
I've started building this, but I'm wondering how often organizers will actually use it. It could end up being seen as extra work to manage, if the only purpose is for stats. If they don't use it, though, then it wouldn't be useful for stats.

Adding the automation could make it easier to process the call for volunteers form, and have a canonical database of folks, but it'd have the same shortcomings as the speaker automation.

What specific stats do we want to have around volunteers? Another approach might be to ask organizers to just give us that aggregated data in the post-event survey. That way they could use whatever system works best for them. That might also have a low participation rate, though, and also inconsistent collection methods, etc 🤔 

Do you have any thoughts @naokomc , @StevenDufresne ?

**Comment by naokomc** [comment]
We'd like to collect 2 things:

- first-time vs returning volunteer
- self-reported diversity data

From what it looks like currently, some pilot events will be using the current WordCamp website, Meetup.com event tool, or something completely different (e.g. Rosetta site news post + external form) for signup. Those events will need to use a survey.

For the pilot events that will use the new event website, we could ask them to use a certain method specified. For example:

- Create separate ticket types for volunteers/attendees/organizers/sponsors
- Include questions about past experience and diversity by copying the exact question & answer and making them mandatory

Does this sound like a good solution?
Will we need anything else for the stats to be pulled later?

**Comment by iandunn** [comment]
🤔 if we use volunteer tickets, and the person marks themselves as a first time attendee, then we could assume that they're also a first-time volunteer. if they're not a first-time attendee, though, then we can't infer if they've volunteered before or not. So, we'd need a separate question for first-time volunteer if we take that approach. 

We'd also need to ask for their w.org username too, in order to get the diversity data from their profile, and complete #550. Those aren't hard, but it is starting to feel like we'd be shoehorning the volunteer data into CampTix. I'm guessing many camps will also want to put out call for volunteers long before they're ready to start selling tickets, too. We'd probably have more flexibility and easier maintenance with a separate post type after all?

If we do use a separate post type, then we could have the site automatically create tickets for volunteers (and speakers) that are accepted. That'd take some work off of organizers, which may offset the added working of managing the post type. The automated ticket would require them using the built-in `Call for Volunteers/Speakers` forms and the process to publish accepted submissions, so updating the docs/mentoring would help.

🤔 I guess I'm leaning more towards going ahead with the post type. If there's not enough usage, can ask why organizers why, and iterate to remove pain points etc. What do you all think?

**Comment by naokomc** [comment]
> We'd probably have more flexibility and easier maintenance with a separate post type after all?

This is true.

Maintaining the WP.org username information for each role will enable us to verify if a person previously held that role. This is a more reliable method compared to checkboxes.

> If we do use a separate post type, then we could have the site automatically create tickets for volunteers (and speakers) that are accepted.

This ability will be very helpful (for speakers/sponsors too), since having people manually switch their tickets after being accepted has been very cumbersome and unreliable.

For pilot events, especially those ones happening in the early phase, we can be more flexible with the website and its tools. As I mentioned, organizers can always share the information via survey results.

**Comment by iandunn** [comment]
I updated https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/web-presence/custom-tools-for-building-wordcamp-content/ with info on the new post type.

That was the last thing needed for this.

**Comment by dknauss** [comment]
Having used this feature for the first time, there are a couple of strong barriers/pain points that sent me looking to figure out exactly what the Volunteers CPT is supposed to do, and what else might be done with it. None of this is answered in the Organizer Handbook documentation [here](https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/web-presence/custom-tools-for-building-wordcamp-content/). So, apart from clarifying the purpose and possibilities for the Volunteers CPT in the handbook, the following barriers to using it exist:

- An "application" to volunteer results in content creation that can be acted on only by editing and publishing (or deleting or ignoring) it. In this context, does publishing = approval (of an application), and does anything happen as a result? There appears to be nothing actually published on the site or sent to the applicant. If this CPT content exists simply to generate a badge for the volunteers, that should be made clear. (This was _not_ the expected behaviour.)
- The applicant indicates team preferences in their application and shares a lot of other info, but this does not appear to carry through into the content or the team taxonomy checklist. The application does not explicitly ask for a bio that could be published, but that could be useful here. Of course that would require a display block for volunteers the way there is for sponsors and organizers — which would make sense. (This _was_ the expected behaviour.)

So, it would make sense to at least clarify that Volunteers content does nothing on the site front-end if published and cannot be accessed at all on the front end or through blocks. 

Or, it would also make sense to make Volunteer content truly publishable. 

Should I create an issue for one or both contingencies?
