### ISSUE TITLE
Enhancement of Event List UI and Redirection Update for Events Domain

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wordcamp.org#894]
To help with the promotion of Pilot Events, we need to add them to the [Community Events](https://href.li/?https://make.wordpress.org/community/events/) list. The usability and user experience of the Community Event Lists can also be enhanced by this action.

- [x] Redirect the URL `events.wordpress.org` to https://make.wordpress.org/community/events/. This will simplify access to the community events list for users.

- [x] Improve the event list user interface to make it easier for users to identify the type of each event. Currently, the events list's layout can be difficult to read and needs some adjustments.

**Potential Option for UI Renewal**
| Before | After |
| ------ | ------|
| ![image](https://github.com/WordPress/wordcamp.org/assets/18050944/0a9320a6-c7a5-4395-a1f3-23e037b19284) | ![image](https://github.com/WordPress/wordcamp.org/assets/18050944/13f70643-8d84-44ad-8f32-8ba5fbcc6ceb) |

Any further thoughts or suggestions on either the UI or the redirection?

**Comment by outdoor2kode** [comment]
@iandunn, could you help verify if the steps I plan to take to redirect `events.wordpress.org` to `https://make.wordpress.org/community/events/` is correct? 

(Referencing from #884)
Make a systems request for:
1. A DNS `A` record that points `events.wordpress.org` to the WordCamp server
2. Updating nginx config to redirect requests for` events.wordpress.org` to `https://make.wordpress.org/community/events/`
3. Updating nginx to use the *.wordpress.org SSL for `events.wordpress.org`

And from what I gather from this [comment](https://nesosoup.wordpress.com/2023/05/17/wordcamps-iteration-new-event-submission/#comment-3002), I guess the subsequent steps in #884 should not be necessary at the moment. Only If there comes a day when we no longer want to redirect and want the website to stand on its own, we'll need to make another request to the system for those steps, is that right?

**Comment by iandunn** [comment]
I don't think we're ready to make the systems request yet, since the Community team is still finalizing the URL. You can test it out locally though, and draft a PR. That way it'll be easy to update with the final URL once the decision is made.

We want requests to `events.wordpress.org/wp-admin`, `/wp-cron.php`, `wp-login.php`, `wp-content`, `wp-json`, etc to be handled by WordCamp.org, but normal front-end requests to go to the make/Community page. I'm guessing it'll need to be an mu-plugin. It's probably be best to setup a new mu-plugin for the Events network we'll create in #885. It could return early if the current site is part of the original WordCamp network (checking `SITE_ID_CURRENT_SITE`).

Related: https://core.trac.wordpress.org/ticket/42061, https://core.trac.wordpress.org/ticket/19898, https://wordpress.stackexchange.com/a/360401/3898. TLDR: We might be able to use `wp_using_themes()` to detect the front end earlier than the `template_redirect`, but will still need an additional `REST_REQUEST` check to make sure it's not a REST API request.

🤔 Fully testing this may need to wait until #884 and #885 are done, though.
