### ISSUE TITLE
Sessions: Image Settings

### ISSUE THREAD

**Issue by melchoyce** [WordPress/wordcamp.org#91]
- [ ] "Image size" should be called "Image Settings"
- [ ] Image Settings should match regular core image settings UI (see Image block)
- [ ] Should be able to hide images

**Comment by coreymckrill** [comment]
Fixed with https://meta.trac.wordpress.org/changeset/8768

> Image Settings should match regular core image settings UI (see Image block)

Because these settings modify multiple images at once that might not be the same size/aspect ratio, we opted to use the same image controls that we're using for avatars in the Speakers and Organizers blocks, rather than emulating the Core image block exactly. More info in #36.
