### ISSUE TITLE
Search for any `wordcamp.org|test` hardcoded strings that may need updating. Ideally we wouldn't have anything hardcoded, except maybe to validate against a safelist of legit domains.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordcamp.org#913]

**Comment by StevenDufresne** [comment]
@iandunn What type of hardcoded strings are you thinking here? I'm not certain I follow which strings would need updating.
 Since we only changed the subdomain, I think anything that points back to `wordcamp.org` is fine? Do you mind providing some brief context?

**Comment by iandunn** [comment]
I was thinking of things like this:

https://github.com/WordPress/wordcamp.org/blob/9029628a085bf949406c0701a407b8180e2d4e45/public_html/wp-content/sunrise.php#L204

That particular one probably won't need anything, since that file wont be loaded on the Events network (see #907), but it seems like a good idea to check the codebase for anything that might need to be aware of the fact that now we have an additional domain being served. If there's code that isn't aware, it might do something we don't expect in this new context.

**Comment by StevenDufresne** [comment]
Ah right. I spaced on the fact that its `events.wordpress.org` not `events.wordcamp.org`. 😵‍💫 

Is it possible to fix these errors as we find them? I like being proactive but i think if we focus on adding relevant tests, we should bring these to light?

**Comment by iandunn** [comment]
That works for me 👍🏻
