### ISSUE TITLE
NextGen WP Event Attendee Satisfaction Survey

### ISSUE THREAD

**Issue by devinmaeztri** [WordPress/wordcamp.org#929]
**Current WordCamp Attendee Survey:** Attendee Survey is not mandatory for organizer to send it to the attendees, and the feedback goes to the organizers, instead of WordCamp Central (we don't have access to the feedback directly).

**Expected Attendee Satisfaction Survey for new WP events:** As part of the learning from experimentation and a default process, we want the Attendee Satisfaction Survey to be mandatory for attendees and they can opt out. We also want it to be attached to the central event dashboard, so WordCamp Central can have access to the feedback of the survey for every event. 

### Attendee Satisfaction Survey

**Start Survey**	

If you recently attended a WordPress event, please take the survey below to help us make them even better in the future.

**Part I. Tell us about you!**

1. How long have you been using WordPress? [Required]

- More than 1 year
- 1 year 
- Less than a year 
- I don't use WordPress yet

2. Which of these best describes you?  [Allow more than one answer]  [Required]

- Personal Blogger 
- Company Blogger 
- Designer 
- Junior Developer 
- Senior Developer 
- Project Manager 
- System Administrator/IT Professional 
- Sales/Marketing/PR 
- Business Owner 
- WordPress Fan 
- Other: (Please specify.)

3. Please provide a link to the WordPress Meetup chapter where you are actively participating.
4. Have you attended WordPress events before? [Required]

- Yes 
- No

5. If yes, please tell us what event, where and when.
6. Which of the following role(s) have you contributed to in the past? [Allow more than one answer]

- WordPress event Organizer
- WordPress event Volunteer
- WordPress event Sponsor
- WordPress event Speaker/Trainer/Facilitator
- Other: (Please specify.)

7. Did this event allow you to experience any of the following roles? [Allow more than one answer] [Required]

- First-time WordPress event Attendee
- First-time WordPress event Organizer
- First-time WordPress event Volunteer
- First-time WordPress event Sponsor
- First-time WordPress event Speaker/Trainer/Facilitator
- Other: (Please specify.)

**Part II. Tell us about the event you attended!**

1. What WordPress event did you attend? * (title, city, year)  [Required]
2. How did you hear about the event? [Required]
3. How satisfied are you with the event? [Required]

- Extremely satisfied
- Satisfied
- Neutral, 
- Dissatisfied
- Extremely unhappy

4. What aspects of the event were valuable to you?  [Allow more than one answer] [Required]

- I was inspired to contribute to WordPress. 
- I got help with a specific WordPress problem. 
- I made new connections. 
- I learned new WordPress skills. 
- I deepened an established relationship. 
- I was inspired to do more with WordPress.
- I contributed to WordPress.
- Other: (Please specify.)

5. What changes would you suggest to the event organizers? [Required]	
6. Would you like to help contribute to WordPress events in the future? [Required]	

- Yes 
- No

7. If your answer is yes, please enter your email address:
8. How likely are you to recommend the event to others? [Required]

- Very Likely
- Likely
- Unlikely
- Very Unlikely

9. If you are willing to answer follow-up questions about this survey, please enter your email address here.	(e.g. [john@example.com](mailto:john@example.com))

**Finish Survey**

Thanks for helping us improve our events by sharing your experience at our WordPress event!

In Google Form for the events happening in July: https://docs.google.com/forms/d/1sXc7OHXm3Fz_cWtuJojW28J7kTOiB7lsIIpgwEhjuf4/edit

**Comment by iandunn** [comment]
@devinmaeztri This is how I'm envisioning it. Does this align with what you were thinking, or would you like to change anything?

1. When a new site is created, we automatically create an `Attendee Satisfaction Survey` page with a `draft` status. The page contains a survey form, and cannot be edited by organizers.
1. The day after the event, we automatically publish the page
1. After publishing the page, we automatically email all attendees a link to the survey
1. Visitors follow the link to fill out the survey:
	<img width="1330" alt="Screenshot 2023-07-27 at 1 43 30 PM" src="https://github.com/WordPress/wordcamp.org/assets/484068/aa3cb0f0-cda1-4cf2-a4cf-6ebb03d33d5f">
1. Submissions are visible to organizers and Central in the event site `wp-admin`:
	<img width="2173" alt="Screenshot 2023-07-27 at 1 44 41 PM" src="https://github.com/WordPress/wordcamp.org/assets/484068/5bffb2bf-ba0c-492f-9f64-819b7d26de94">
1. Central has a dashboard that links to all of the sites that have responses. It goes directly to the feedback responses page in the event site's `wp-admin`:
	<img width="1005" alt="Screenshot 2023-07-27 at 2 18 42 PM" src="https://github.com/WordPress/wordcamp.org/assets/484068/b9de7728-be63-42a9-8d03-99c9ba1761f9">
1. After 2 weeks, we un-publish the page and stop accepting responses (to prevent spam etc)

Notes:
* Creating the survey in the database (rather than having a hardcoded template) means that, when the questions change, those changes would only apply to new sites created after the change. Sites that have stopped collecting responses, or are in the mid-collection process would not be updated. That can be a good thing, since changing the questions mid-collection would make it harder to compare responses before and after the change. 
* There aren't any mechanisms to tie responses to a specific attendee. That can be a good thing for privacy, but can also result in spammers, etc filling out the form, someone accidentally filling it out twice because they forgot they already had, etc. We could add those in a later iteration, though.
* Another future iteration could be emailing folks who haven't filled out the form to remind them to do it. That could be done a few days before responses are closed.

**Comment by iandunn** [comment]
> Please provide a link to the WordPress Meetup chapter where you are actively participating.

This assumes that they are actively participating, but many attendees won't be. What do you think about changing the phasing to `Please provide link(s) to any WordPress Meetup chapters where you are actively participating.` ?

**Comment by timiwahalahti** [comment]
I'd suggest changing the word `chapter` to `group` to align the terminology used on meetup.com and most Community Team messaging.

**Comment by timiwahalahti** [comment]
Related discussion in #community-event-supporters https://wordpress.slack.com/archives/C04L4HPFGHX/p1690552731165619

**Comment by devinmaeztri** [comment]
Hello @iandunn and @StevenDufresne! 

> When a new site is created, we automatically create an Attendee Satisfaction Survey page with a draft status. The page contains a survey form, and cannot be edited by organizers.

Similar to Organizer Survey, the goal is for WC Central (Program Supporters/Managers) to have access to the feedback easily and download them easily too, without relying on Organizers to share the feedback with us or move to a different platform. We also hope the surveys are sent by default after the Camp completes. However, as we are still experimenting, we want to have the flexibility to make improvements on these surveys. 

> - The day after the event, we automatically publish the page
> - After publishing the page, we automatically email all attendees a link to the survey
> - Visitors follow the link to fill out the survey:
> - Submissions are visible to organizers and Central in the event site wp-admin:
> - Central has a dashboard that links to all of the sites that have responses. It goes directly to the feedback responses page in the event site's wp-admin:
> - After 2 weeks, we un-publish the page and stop accepting responses (to prevent spam etc)

These steps sound good to me! Thank you!

> That can be a good thing, since changing the questions mid-collection would make it harder to compare responses before and after the change.

I agree!

> That can be a good thing for privacy, but can also result in spammers, etc filling out the form, someone accidentally filling it out twice because they forgot they already had, etc. We could add those in a later iteration, though.

Makes sense!

> Another future iteration could be emailing folks who haven't filled out the form to remind them to do it. That could be done a few days before responses are closed.

I like this! We are not getting a lot of responses from Sevilla and Leipzig after a month. We actually gave 2-week deadline, although we don't close the form. Furthermore, we only received responses from about 30% of the attendees. In fact, I'm struggling to get the feedback from one of the organizers. Similar to the fact that most of WordCamp Lead organizers are not submitting the Camp Debrief.  

> This assumes that they are actively participating, but many attendees won't be. What do you think about changing the phasing to Please provide link(s) to any WordPress Meetup chapters where you are actively participating. ?

Yes, we are revising a similar question in the application too! `If you are a member of a WordPress Meetup group, please share the URL.`

**Comment by StevenDufresne** [comment]
> In fact, I'm struggling to get the feedback from one of the organizers. Similar to the fact that most of WordCamp Lead organizers are not submitting the Camp Debrief.

Automating something that isn't working well gives me some pause, but I can see the management burden that will arise in the future. I think we could incentive responses better later, maybe connecting it to the "badge" project that hopes to introduce more one time badges. Maybe you get your X Event badge for providing feedback... I'll save that conversation for the future.

**Comment by StevenDufresne** [comment]
Related to:

> Did this event allow you to experience any of the following roles? [Allow more than one answer] [Required]

I don't know it makes sense to have an "other" input here since the roles that we lead with are so specific to "First Time". Would I need to answer something prefaced with "First time"? We also are looking for a specific answer to did you experience these roles "X,Y,Z". This question feels really closed. It's also a required field, so I'll have to come up with an answer. 

cc @devinmaeztri

**Comment by StevenDufresne** [comment]
Also:

> What WordPress event did you attend? * (title, city, year) [Required]

We already know that. They are emailed from an attendee list. Can we remove this? @devinmaeztri

**Comment by devinmaeztri** [comment]
> I don't know it makes sense to have an "other" input here since the roles that we lead with are so specific to "First Time". Would I need to answer something prefaced with "First time"? We also are looking for a specific answer to did you experience these roles "X,Y,Z". This question feels really closed. It's also a required field, so I'll have to come up with an answer.

Hello @StevenDufresne! It was taken from the WordCamp Attendee Survey and the original question is `Please tell us more about your event experience by rating the below statements.` We actually combined 2 questions in the WordCamp Attendee Survey. 

So we use the question `Please tell us what aspects of WordCamp were valuable to you.` and use the options from the other question. 

If removing "Other" makes sense. Let's do that!

**Comment by devinmaeztri** [comment]
> What WordPress event did you attend? * (title, city, year) [Required]

Ah yes, we added it as we thought we will use the same Google Form for all pilot events. Although I made copy for each of the implemented pilot event. 

So removing this question makes sense as we will have it included in every event site. Thank you!

**Comment by StevenDufresne** [comment]
@devinmaeztri Do you have the content of the email that will have the link?

**Comment by devinmaeztri** [comment]
Hello @StevenDufresne! We have not prepared it. I'll look at the WordCamp one and make some adjustments.

**Comment by devinmaeztri** [comment]
Hello @StevenDufresne!

Here is the email template:

NextGen Event Attendee Survey Email

Hi [NAME],

[NEXTGEN EVENT NAME] is over, thank you to everyone who joined us!

As a community-led event, feedback is really important to us. It helps us improve our events and to keep providing high quality content. 

Please take a moment to answer our <LINK survey LINK> and help us to do amazing WordPress events!
(If you can't open the link, copy and paste the following URL)
 [LINK TO THE SURVEY].
 
Please complete the survey by [DATE]. 

Please also note that all responses will be kept confidential, and we will not share your personal information with any third parties.

Thank you in advance, we really appreciate your time!

Best regards,
Organising Team,
[NEXTGEN EVENT NAME]

**Comment by outdoor2kode** [comment]
Some notes after reviewing the PR of this ticket:

> I think we could incentive responses better later, maybe connecting it to the "badge" project that hopes to introduce more one time badges. Maybe you get your X Event badge for providing feedback... I'll save that conversation for the future.

Second the idea of incentivizing responses like filling out an attendee survey, and giving those who’ve done it a badge like `providing feedback total X events`.

>  In fact, I'm struggling to get the feedback from one of the organizers. Similar to the fact that most of WordCamp Lead organizers are not submitting the Camp Debrief.

Likewise, perhaps we can consider adjusting the mechanism for giving badges to WordCamp organizers, only when organizers complete all the tasks or at least certain required tasks on the planning checklist (`/wp-admin/index.php?page=wcm-planning-checklist`) then they can get the badge.

> Can organizers see the survey analysis?

Currently, organizers can view attendee survey responses from the event site admin's feedback, but they can't see the more detailed data in the Attendee Survey like the Central admin can. I understand that the data in the Attendee Survey now are all Next-Gen Event data and only include Total Responses and Response Rate. But I think that even the Response Rate is a metric that organizers would care about. And in the future, there's also potential to add more statistical data. 

Would it make sense, in future iterations, to allow organizers to see the attendee survey stats for the events they've organized? 

I've noticed that one reason organizers sometimes use third-party tools is that they can easily access the stats they want. And since organizers for one event often continue in that role for subsequent events, much of this data is crucial for them to improve and base their future actions on.

cc @devinmaeztri

**Comment by devinmaeztri** [comment]
> Second the idea of incentivizing responses like filling out an attendee survey, and giving those who’ve done it a badge like providing feedback total X events.

Would it be possible to have completing event surveys (organizer, attendee, etc - including WordPress survey, Meetup survey) as part of Activity, such as what we see in the screenshot?

<img width="612" alt="Screenshot 2023-09-05 at 16 37 31" src="https://github.com/WordPress/wordcamp.org/assets/75025757/7758a08b-4258-4ab3-904e-44049b7a59e3">

> Would it make sense, in future iterations, to allow organizers to see the attendee survey stats for the events they've organized?

Yes, I agree for the same reasons you have outlined. That way we all can learn from the data.

Thanks, Ren!
