### ISSUE TITLE
Check `switch_to_blog( BLOG_ID_CURRENT_BLOG )` calls. 

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordcamp.org#936]
# Summary
 Check `switch_to_blog( BLOG_ID_CURRENT_BLOG )` calls. Some should continue using using `BLOG_ID_CURRENT_BLOG` (which will be the `events.wordpress.test` root blog on the Events network), and some will need to be updated to use `WORDCAMP_ROOT_BLOG_ID`, because they should still switch to `central.wordcamp.test`, even when called by sites on the Events network. https://core.trac.wordpress.org/ticket/25293 and https://core.trac.wordpress.org/ticket/40513 might be relevant.

## References

Checked list items do not require any updates.

- [x] wordcamp.org/public_html/wp-content/mu-plugins/camptix-tweaks/camptix-tweaks.php
```
  677,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordpress.org
  773,4: 			switch_to_blog( BLOG_ID_CURRENT_SITE );
  800,3: 		switch_to_blog( BLOG_ID_CURRENT_SITE );
  848,2: 	switch_to_blog( $site_id );
```

- [x] wordcamp.org/public_html/wp-content/mu-plugins/4-helpers-wcpt.php
```
  51,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE );
  81,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE );
  114,2: 	switch_to_blog( $site_id );
  254,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordcamp.org
  327,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE );
  361,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE );
  382,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE );
```

This `switch_to_blog` calls are fine, but the hardcoded `post_type => 'wordcamp'` will need to be addressed. 

- [x] wordcamp.org/public_html/wp-content/plugins/wc-post-types/wc-post-types.php
```  
1269,4: 			switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordcamp.org .
```
I think we'll keep the sponsors separate for now. So this should be ok.

- [x] wordcamp.org/public_html/wp-content/plugins/wcpt/wcpt-wordcamp/wordcamp-new-site.php
```  
296,3: 		switch_to_blog( $blog_id );
  424,3: 		switch_to_blog( $this->new_site_id );
  483,80: 		delete_option( 'rewrite_rules' ); // Delete because can't be flushed during `switch_to_blog()`.
  829,3: 		switch_to_blog( BLOG_ID_CURRENT_SITE ); // Switch to central.wordcamp.org.
  852,3: 		switch_to_blog( BLOG_ID_CURRENT_SITE ); // Switch to central.wordcamp.org.
```

- [x] wordcamp.org/public_html/wp-content/plugins/wordcamp-dashboard-widgets/wordcamp-dashboard-widgets.php
```   
 71,4: 			switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordcamp.org.
```    

- [x] wordcamp.org/public_html/wp-content/plugins/wordcamp-reports/includes/validation.php
```    
137,15: 		$switched = switch_to_blog( BLOG_ID_CURRENT_SITE );
```

**Comment by StevenDufresne** [comment]
@iandunn Looking through the references, I couldn't find any that needed updating; which is suspicious. Can you verify?

**Comment by iandunn** [comment]
>  254,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordcamp.org

🤔 That's the first one I checked, and I think it's fine to leave it as `BLOG_ID_CURRENT_SITE`, since we'll want to use that function for pilot events too. There are other some changes we might want to make in that function if we're looking at it holistically, though:

* The `$wpdb->posts.post_type = 'wordcamp' AND` bit of the SQL query would need to be updated to reference `WCPT_POST_TYPE_ID` and `WCPT_PILOT_EVENT_SLUG`, based on the current network
* `Select a WordCamp` string should include "pilot event" if the current network is events.wordpress.org
* Remove the `// central.wordcamp.org` comment since that's no longer always true

I think that'll be true of many of the other plugins. The presence of `switch_to_blog()` is an indication that the entire function (and maybe surrounding functions or entire file) contains code that needs to be audited.

Ideally we'd also update things like the function name, the `$name = 'wordcamp_id'` variable, etc, but that's probably not practical, and may be premature. If we don't, though, we're adding some tech debt, so it may be worth looking into in a future milestone.

I'll check some others too.

**Comment by iandunn** [comment]
Doh, it looks like you already most caught those in #937 , nice!

**Comment by iandunn** [comment]
>  677,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordpress.org
> 773,4: 			switch_to_blog( BLOG_ID_CURRENT_SITE );
> 800,3: 		switch_to_blog( BLOG_ID_CURRENT_SITE );
> 1269,4: 			switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordcamp.org .

🤔 Those will all probably depend on how the global sponsor financials with work. @devinmaeztri, will the global sponsors be the same for WordCamp and pilot events, or will there be any differences?

**Comment by iandunn** [comment]
This one will need the new `get_wordcamp_post_type()` function from #937:

https://github.com/WordPress/wordcamp.org/blob/18642950aa9b4bcd8647945290e6b86bf2210bb1/public_html/wp-content/plugins/wordcamp-reports/includes/validation.php#L142

Other than that, the only things I saw that need updating were all the comments that mentioned `central.wordcamp.org` for `BLOG_ID_CURRENT_SITE`. Those should be removed, or updated to reflect that it could be either root site. Sometimes those comments appear above the `switch_to_blog()` line, rather than on it.

**Comment by iandunn** [comment]
The `mu-plugins-private` folder will also need to be checked for everything in #906, but it doesn't look like any of the `switch_to_blog()` functions will run on wordcamp.org, so nothing is needed in this PR. All of those calls are in `wporg-mu-plugins/` and not explicitly activated by `wporg-mu-plugins.php`.

**Comment by StevenDufresne** [comment]
> 🤔 Those will all probably depend on how the global sponsor financials with work. @devinmaeztri, will the global sponsors be the same for WordCamp and pilot events, or will there be any differences?

How often do Global sponsors change? If not often, I would vote that we duplicate the data and turn it on for the events network while we work through this and cycle back later. The "Multi Event Sponsors" plugin would require a number of adjustments to get it working properly.

**Comment by devinmaeztri** [comment]
> > 677,2: 	switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordpress.org
> > 773,4: 			switch_to_blog( BLOG_ID_CURRENT_SITE );
> > 800,3: 		switch_to_blog( BLOG_ID_CURRENT_SITE );
> > 1269,4: 			switch_to_blog( BLOG_ID_CURRENT_SITE ); // central.wordcamp.org .
> 
> 🤔 Those will all probably depend on how the global sponsor financials with work. @devinmaeztri, will the global sponsors be the same for WordCamp and pilot events, or will there be any differences?

Yes, they will the same for WordCamps and New Events. The Global Sponsors change every year. But sometimes, we have new Sponsors joining in the middle of the year.

**Comment by StevenDufresne** [comment]
I'm going to close this, because none of the references seem to need to pull from the central network. The issue with the multi-event sponsor will be moved to another issue.

**Comment by iandunn** [comment]
If we're not creating duplicate Multi Event sponsors on the Next Gen network, then wouldn't all of those need to be updated to pull from `WORDCAMP_ROOT_BLOG_ID` ? Otherwise they'll try to pull from `EVENTS_ROOT_BLOG_ID` on Next Gen sites, and get an error because the post type won't exist there.

Since the sponsors will be the same between event types, I think it makes sense to use the existing posts on Central for all both networks.

**Comment by iandunn** [comment]
Er, it looks like there's a new issue to track that -- #951 -- so this can be closed after all.
