### ISSUE TITLE
Class names don't follow convention

### ISSUE THREAD

**Issue by iandunn** [WordPress/wordcamp.org#96]
If I understand [the guidelines](https://wordpress.org/gutenberg/handbook/contributors/develop/coding-guidelines/) correctly, it seems like all of our class names are wrong, and should be renamed to the BEM-esque convention 😱

e.g.:

* `wordcamp-speaker-sessions-list` should be `wordcamp-speaker__sessions-list`.
* `wordcamp-image-container` should be `wordcamp-avatar` (or `wordcamp-avatar__container` if we want to keep the redundant descriptor)
* `wordcamp-item-permalink` should be `wordcamp-block-content__item-html-content-permalink`, or maybe `wordcamp-block-content__item-html-content__permalink`? Those would both be awful, so maybe (hopefully) I'm reading the guidelines wrong? Maybe `wordcamp-item-html-content__permalink` if we want to break the guidelines for sanity's sake?
* `wordcamp-image-link` should be `wordcamp-featured-image__link`
* `wordcamp-clearfix` should be `wordcamp__clearfix`

Those are just a few examples, but it seems like probably every single class needs to be renamed 😢. I hope I'm wrong.

If not, we should probably fix this before launch since fixing it in the future would break BC.

@coreymckrill , @vedanshujain : what do you think?

**Comment by iandunn** [comment]
The BEM-esque style is nice, because it matches the component structure, but using it would also create inconsistency across our codebase. That would be especially inconvenient for organizers, when they're trying to style the front-end.

However, that inconsistency already exists, since the Core blocks use the BEM style, while everything else output by Core follows [the current standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).

It turns out that the inconsistency has been discussed a few times:

* https://github.com/WordPress/gutenberg/issues/11689
* https://wordpress.slack.com/archives/C02QB2JS7/p1496251618220866

Unfortunately, that wasn't resolved before the 5.0 merge, so now we're left dealing with the fallout.

It's unclear whether the Gutenberg standards will be merged into Core at some point in the future. Obviously there'd be some back-compat hurdles to overcome if they are; I'm guessing the only way to do it would be to add duplicate BEM-style classes everywhere that currently has WP-style classes (for lack of a better term). That would be awkward, cluttered, and somewhat ineffective :(

I guess no matter what we do here, there's going to be some inconsistency on front-end for organizers. If we continue using `wordcamp-{block}-{thing}`, then we'll minimize inconsistency to only the Core blocks, but if we switch to `wordcamp-{block}__foo` then we'll be consistent with other blocks, and **maybe** with Core's future standards.

I can see compelling arguments for both sides. I feel like I'm leaning a bit more toward avoiding the BEM style, in order to minimize the inconsistency, but I'd like to sleep on it a bit, and get some input from @coreymckrill and @vedanshujain.

Either way, I think it's good for us to continue using the `wordcamp-{block|component}` prefix, to avoid collisions.

**Comment by andreamiddleton** [comment]
Mild opinion, loosely held: I think that we follow the Gutenberg CSS standards, because this inconsistency in standards seems likely to become the new normal. If this project is a friendly introduction to working with Gutenberg for most organizers, then we should introduce them to a standard Gutenberg experience.

**Comment by andreamiddleton** [comment]
FWIW, the longer I sit with this mild opinion, the more I'm convinced that I'm right. :) Does anyone want to debate this, or do we want to move forward with the two different coding standards plan?

**Comment by iandunn** [comment]
🤔 , yeah, I'd be ok with that. I think they're both bad options. Anyone object?

**Comment by andreamiddleton** [comment]
I agree they're both bad options. :) Dislike all the way around! But we have to make a decision, so. ;)

**Comment by coreymckrill** [comment]
No objections here.

**Comment by coreymckrill** [comment]
Reading through [the guidelines](https://wordpress.org/gutenberg/handbook/contributors/develop/coding-guidelines/) again, there are some logistical things we need to figure out in order to adapt them to our codebase:

* I assume we'll want to pre-prefix everything with `wordcamp-`.
* For this:
  > All class names assigned to an element must be prefixed with the name of the package, followed by the name of the directory in which the component resides.

  Would we consider each block to be a package, or just "blocks"? `wordcamp-blocks-organizers__` seems kind of excessive. `wordcamp-organizers__` might be better? And then there's "components". Should we go with `wordcamp-components-post-list__` or could we just do `wordcamp-post-list__`?
* For state class names, we don't have that many, but one that we're using for image alignment currently is, e.g. `align-center`, `align-right`. The guidelines suggest these should instead be `is-aligned-center` and `is-aligned-right`. But the versions we're using now are already widely used in other places in WordPress. Which way should we go? Also adding block support for full and wide layouts adds `alignwide` and `alignfull`, which is yet another different naming convention :/
* Right now all of our styles are transpiled into one file, `blocks.min.css`. This includes front end and editor styles, and the file is loaded on both the front and back end. This was mainly done because I couldn't figure out how to generate a transpiled CSS file that didn't correspond to a JS file of the same name, and it seemed stupid to have an empty JS file named `editor.min.js`. But the guidelines say there should be separate files for front and back (which makes sense!). Should we work on a way to separate these as part of this issue?

**Comment by iandunn** [comment]
> wordcamp-blocks-organizers__ seems kind of excessive.

💯 

In Gutenberg, they do use `components` as the package, but if I understand it correctly, I think  they're doing that because `components` is the name of the literal npm package that they publish (minus the `@wordpress/` prefix). If they want it to truly be an independent package that can be reused outside of Core and even outside of `@wordpress/block-editor`, then they can't have a prefix like `wordpress`, etc.

I can see how that makes sense in isolation, but I think it immediately breaks down when you use it in the real world, with Gutenberg as part of Core and all manner or plugins running.

If we were to distribute this as a package, I guess we'd call it `@wordcamp/blocks` ? So then by that logic `blocks` should be the prefix, but that'd be obviously bad, for the same reasons that `components` is bad.

The package definitely has to be unique, but I agree that `wordcamp-blocks-organizers__` is excessive. I'd say `wordcamp-organizers__` and `wordcamp-post-list__` is fine. That feels like it follows the spirit of the guidelines, if not the letter. 

For us the `block/` and `component/` folders are just transparent organizational devices for the filesystem, rather than part of the actual component hierarchy in the DOM. Maybe that's a useful way to think about it?

>  the versions we're using now are already widely used in other places in WordPress.

I would think we'd want to go w/ the Gutenberg convention, for the same reasons that we're moving all the other classes to that.

As far as _what_ that convention is... good question :)

🤔 It seems like they're not thinking of alignment as a state, which I guess I can see. That, or they're just not internally consistent, which is also possible :)

At least for the Image block, if you view the front-end, the containing `<figure>` has `aligncenter`, `alignright`, etc, without a dash. So I guess we should do the same.

> Should we work on a way to separate these as part of this issue?

Nah :)

This is already a bear, let's open another issue for that. I don't think it's a v1 blocker, though.

**Comment by vedanshujain** [comment]
Fixed in https://github.com/WordPress/wordcamp.org/pull/123
