### ISSUE TITLE
Fix `add_wcpt_cross_link` function

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/wordcamp.org#961]
Function `add_wcpt_cross_link` in `mu-plugins/wcorg-misc.php` should be placing a 'WordCamp Post' link to the admin bar menu on camp sites. At the moment, that functionality does not seem to work. Let's fix that, since the idea is excellent!

https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/mu-plugins/wcorg-misc.php

**Comment by timiwahalahti** [comment]
Works as intended, was a fault on Docker data.

**Comment by timiwahalahti** [comment]
On the Docker env this seems to work, but for some reason on production I can't see the WordCamp Post link 🤔

**Comment by iandunn** [comment]
It seems to be working for me on production:

<img width="356" alt="Screenshot 2023-07-20 at 11 03 33 AM" src="https://github.com/WordPress/wordcamp.org/assets/484068/665184e9-c220-4d59-89fa-8280567d0db2">

Which site are you seeing it not work? It may be that that site's corresponding wordcamp post doesn't have the `_site_id` post meta.

**Comment by timiwahalahti** [comment]
Tested Europe 2023, 2022 & 2019 and Finland 2023.

<img width="206" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/415544/3b476c00-c14e-43f6-b074-f24df358e339">

**Comment by iandunn** [comment]
Ah, I think it's because the capability only gets added on Central

https://github.com/WordPress/wordcamp.org/blob/b2b993ccf9390325ebf04d942f9c88191313e63b/public_html/wp-content/mu-plugins/wcorg-subroles.php#L59-L67

🤔 I wonder if that was just a precaution, since at the time the caps were only checked on Central?

I can see two solutions:

1. Update the code above to grant the caps everywhere. We'll want to make sure there wasn't a more tangible reason they were originally only on Central, but none come to mind at the moment.
2. Update `add_wcpt_cross_link()` to switch to Central before checking caps. It'll be doing that anyway to get the post. We'd need to grab the current site ID before switching and pass it to `get_wordcamp_post()` since that function won't be able to get it anymore.

**Comment by timiwahalahti** [comment]
The latter sounds safer, although can't think of a reason why `wordcamp_wrangle_wordcamps` couldn't be granted outside Central.

Tho thinking little longer, having `wordcamp_wrangle_wordcamps` cap would be nice. For example, see https://github.com/WordPress/wordcamp.org/pull/949/files#diff-6afecbeec82666ed001ec71cf70723d51fa41616b63b9285fe51542357af120aR214-R217. Of course one could use `is_deputy` function there.

**Comment by iandunn** [comment]
It looks like `mentor_wrangler` originally granted `edit_posts` and `edit_published_posts`, so that might explain why it was restricted to Central.

https://github.com/WordPress/wordcamp.org/blob/c02f630466cc47979b940a41dbac0dfdf0bba149/public_html/wp-content/mu-plugins/wcorg-subroles.php#L54-L55

Those were removed in b3bdd96f0cbafaf8b0f4f8c23462340a899e0a89, but the commit doesn't say why. With those caps gone, it seems fine to remove the Central condition.

**Comment by iandunn** [comment]
This is deployed now, let me know if it doesn't work for you.
