### ISSUE TITLE
WordPress NextGen Event Budget Enhancements

### ISSUE THREAD

**Issue by harmonyromo** [WordPress/wordcamp.org#976]
With the introduction of NextGen WP Events, and the work that is being done to update the organizer dashboard and tools, there are several budget tool updates that could make it more functional for organizers and Central.

 - [x] Under Event Data > Days (please create a drop down for the following)

`Days`

`Hours`

- [x] Instead of Event Data > Tracks (Lets use format options as drop downs instead)

- WP Expertise Level (beginner, intermediate, advanced)
- Focused Activity (workshops, networking, contributing)
- Job Status (students, job seekers, business owners, freelancers)
- Identity Based (women, BIPOC, LGBTQ+, age, accessibility needs)
- Content Topic Focused (hosting, block development, designers)
- Other

- [x] Under Event Data > Speakers, please update `Speakers` to `Facilitators`
- [x] Under Expenses > Can we remove `Speaker Event`, `After Party`, and `Camera Shipping` as expense categories

**Comment by iandunn** [comment]
@harmonyromo , should any of these changes apply to traditional WordCamps as well, or only to NextGen events?

**Comment by harmonyromo** [comment]
@iandunn These are the items specific to NextGen events.

**Comment by tellyworth** [comment]
In terms of implementation (following up on a conversation with @renintw ), a few quick thoughts:

I think we probably need global functions along the lines of `is_next_gen()` and `is_og_wordcamp()` to help with code clarity. Or alternatively, `is_event_type( 'nextgen' )` etc.

Some of the code that's relevant here is in JS, so we'd probably also need equivalent conditionals there too. For example I think the Hours code would need to be added here amongst other places:

https://github.com/WordPress/wordcamp.org/blob/693615629b9e1a35ce6ffb0e281e196a5953dfed/public_html/wp-content/plugins/wordcamp-payments/javascript/budget-tool.js#L272

I think probably this is mostly case-by-case stuff. It'd be nice to think we could refactor some of the templates but that's not likely to be the most efficient way to get it done.

**Comment by outdoor2kode** [comment]
Hey @harmonyromo 👋 

> @iandunn These are the items specific to NextGen events.

So you don't expect to see the changes also applied to the budget tool of [central](https://central.wordcamp.org/wp-admin/admin.php?page=wordcamp-budget) and [local/flagship WC dashboard](https://us.wordcamp.org/2023/wp-admin/admin.php?page=wordcamp-budget), it that right? Only want to see the mentioned items applied to [NextGen](https://events.wordpress.org/wp-admin/admin.php?page=wordcamp-budget) and its [event](https://events.wordpress.org/rome/2023/training/wp-admin/admin.php?page=wordcamp-budget).

>  Under Event Data > Days (please create a drop down for the following)
>
> Days
> Hours

The "Days" field was originally an input for users, but since we'd like it to be a dropdown. Do you have an expected range of options? Perhaps we can set it to range from 0-31, which should be enough? And for the "Hours", I will set the options to range from 0-23.

**Comment by harmonyromo** [comment]
@renintw That is correct. The changes listed are those that we anticipate will differentiate these events from traditional WordCamps. I do know that in certain areas of the world, the community is hesitant to move away from the WordCamp name, but they are willing to update formatting. However, we have to draw the line somewhere, so I would say that, yes, please proceed with these changes only affecting Nextgen events.

As far as the drop down is concerned, I would rather the drop down selection be either the word "Days" or " hours" and allow the organizer to enter the number. My wording may have been confusing on that one. I like allowing the organizer the enter the number. I just wanted there to be an "hours" option in addition to "days", since some events may only span an afternoon or a morning.

**Comment by outdoor2kode** [comment]
@harmonyromo I get it. Thanks for the clarification 🙂  

1. So it will be the cell highlighted in the img below changed to a dropdown with options "Days" and "Hours".
<img width="632" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/6f82a7b5-8e95-45ca-933c-2ea672eaa7e9">

2. And do you see that we need any changes for items that use `per day`? 
(**Update**: I've made it `per hour` when `Hours` is selected first, see video [here](https://github.com/WordPress/wordcamp.org/pull/1003#issue-1848767569))

<img width="1259" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/e5c00ffa-85e8-4bc2-94e7-7558a92aeece">

---

3. What do you envision for the dropdown replacement of Track?
<img width="639" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/0432afe8-4e1e-48c6-bf50-4b1739bde64e">

I'm guessing the plan is to remove 'Track', add in the mentioned fields, the result might be like the image below shows, and set their values to dropdowns? That seems quite sensible. 

But I'm not sure about the `Other` field, is it expected to be placed directly here? I'm leery that users might be confused about what this field is intended for, since it doesn't explicitly denote that `Other` pertains to the other fields within the red box. Or that's not a problem at all?

![image](https://github.com/WordPress/wordcamp.org/assets/18050944/b077012e-6244-42c1-8618-bedbbb039379)

4. Similar to 2. above, I presume we need to remove the `per track` here, but is there anything specific you'd like to replace it with?
(**Update**: I've removed `per track` first)

<img width="1245" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/a41eb8a1-7326-4275-995b-e2cb12cf8539">

**Comment by renintw** [comment]
Thanks for the insight sharing @tellyworth!
> I think we probably need global functions along the lines of is_next_gen() and is_og_wordcamp() to help with code clarity. Or alternatively, is_event_type( 'nextgen' ) etc.

I like the idea of global functions, it reduces duplications and facilitates clarity to an extent.
If we're doing this way, where would be a suitable place to put this kind of function for WordCamp? I can see that there are `mu-plugins` and `mu-plugins`private`, or it can just be put at the first level of wp-content?

I'm tempted not to include the network detection in this PR, as upon diving deeper into the code, I found that the changes needed for the issue are more than initially anticipated.

cc @StevenDufresne

**Comment by harmonyromo** [comment]
Hi @renintw Thank you for all of this. Let me try and address all the questions you have:

1. You are exactly right here. That's what I picture.
2. In trying to think about how this "Per Person" calculation would be used, I'm almost wondering if we take the "per day" and "per hour" out all together, and instead have it just be the total cost per person for the event as a whole. To me, that makes the most sense, and hopefully, that's an easy change.
3. For "Track", I would like to replace the word "Track" with "Format" and then in the value box have the drop down format options you list. 
4. I think we can remove "per track" and just leave that option out altogether. I don't think the "per day" option gets much use either, so I am fine removing those as variable calculation options.

**Comment by outdoor2kode** [comment]
Hey @harmonyromo, thanks for the input!

2. `total cost per person` sounds good 👍 
3. Is this dropdown something you picture? option group name followed by options
<img width="181" alt="image" src="https://github.com/WordPress/wordcamp.org/assets/18050944/a39d6f41-3559-40a0-b1d1-980534eda24d">

4. 👍

**Comment by harmonyromo** [comment]
That looks really great! I like the added details.

**Comment by outdoor2kode** [comment]
Per the discussion with @harmonyromo, this will be the final look 👇 

![image](https://github.com/WordPress/wordcamp.org/assets/18050944/5c759340-b466-4726-bc05-62dd3fa51d41)
